#!/usr/bin/env python3
# Curate Mahaperiyava / Deivathin Kural Volume 1 batch 046..065.
#
# Run from pramana repo root on branch:
#   mahaperiyava-dk-v1-corpus
#
# Recommended:
#   python ~/Downloads/curate_mahaperiyava_dk_v1_batch_046_065.py --commit --push
#
# This semantic curation pass creates 105 metadata-only teaching units across
# 20 chapters. All authority remains dk_attested.
#
# Evidence discipline:
# - exact DK source text remains private/gitignored;
# - every one of the 212 private source paragraphs is accounted for exactly once;
# - no historical-witness promotion is made in this pass;
# - no DK print check or primary-source verification is claimed;
# - all replacement-decoded source chapters are explicitly flagged;
# - context-sensitive social, political, caste/varna, historical, scientific,
#   health/effect, ritual, and comparative-religion claims remain attributed;
# - chapter 61's source title anomaly is preserved rather than silently corrected.

from __future__ import annotations

import argparse
import base64
from collections import Counter, defaultdict
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Any
import zlib

ROOT = Path.cwd()
EXPECTED_BRANCH = "mahaperiyava-dk-v1-corpus"

PRIVATE_PACKET = ROOT / "data/private/mahaperiyava_dk_v1_batch_046_065_review_packet.json"
SCHEMA = ROOT / "schema/teaching_record.schema.json"
CATALOG = ROOT / "data/review/mahaperiyava_deivathin_kural_v1_catalog.json"
QUEUE = ROOT / "data/review/mahaperiyava_deivathin_kural_v1_extraction_queue.jsonl"

TEACHING_RECORDS = ROOT / "data/review/mahaperiyava_dk_v1_batch_046_065_teaching_records.jsonl"
CURATION_INDEX = ROOT / "data/review/mahaperiyava_dk_v1_batch_046_065_curation_index.json"
RESEARCH_MD = ROOT / "data/research/mahaperiyava_dk_v1_batch_046_065_teaching_units.md"
TEST = ROOT / "tests/test_mahaperiyava_dk_v1_batch_046_065_teaching_records.py"
REPO_SCRIPT = ROOT / "scripts/curate_mahaperiyava_dk_v1_batch_046_065.py"

PAYLOAD_B64 = "eNrcvemOJMmWHvYqgf4d3bB9ufwhUBqJGkgUCQ01BEEIAVszoyuWZCxVN4cgMK8hgHy5eRJ9x8zdY8nIzMiq6nur7ixdVZkRbubu57Pznf2//vIU0qdyWOwfwy9/+qWInFkOWjBmFUtKOJlKscWnomQoSnGeotGSex29ztonUbJ2TJbEmPLsl/kv5c9PJR1KXmx3ebkJq/0vf/rPysyVnSs3V36u2VzzuRZzLedazbWeazPXdq7dXPu5YXPD50bMjZwbNTf6/z274nGzPCzS9rg54KL/9RdlfvmTnv+i7C9/MvjD/fIniz98+0Oz9kPN20e06P+Sv/xJ4Q/VP6L7H/0q2vbfuf4v3/4wrP/B2+8MriLxR7+KUf0PXMX8t/kvtDe61f/6yzLjQa7DY3gqu+Vz+Bx+y2X5ORwel5vFp+MurH77zH/bhz1+sAvrsFiHTdiHQ3rEh3/Lj2GHn+Ft7A+7sAj7xWaLHxyWn8siHA+P293y8IynnHD5Q9mNDxlbMacf7lfHB+zhlTV+6ZsdP3X3iquwXC/2x/U67J7xvb9r35sN35st97OnXdmXDV7ULOxnh8cymy40my40q9vdLBfscr3cLDcPs778fIbf9u8etl/CLrfvfymrGnZltq2zsFrNYsEX9rMdHmXZ4QNhM8Mj3m9x/7R2LbuySeU37PW/HMv+sNxuFktcsknLf/7lf99+meVt2c/+7dmrwVb2abeMpa23267aYvnq1jb4WFpm2u6Xx3Cge+0f+Z+w1n98fJ7RJqetrJafsErY5Fle7vs/lpv9sdZlolscnsBwvfE6EPP99rhLZfEUduFhF54eF8vcNv7EGL/5e2zvsbSP6GxiTVLKpIoMSVUnghIhChkrw0+ccN6EVJgV3OBDAqjWlXMdLFfVOLr8Yfu0TO1qfU+4NXo0TwcS2QtJKJAqfBLfqavw0L6Cx5SX9MTx0ZP4NJHBF85/e3bN/mtc5mm3fdruAfDTKpDLT4twOOA9loxLPC73B/wm4WtflodN2WPZzXG1+m/zbwTc55Ih/GssulzsyirQNvePy6fvirG3FrmC1X+AHP4jPn4TULvt9nAS0PkMj+Jx1q/bBe5ScI+bDKE8bLftAlg3bnd97dnDbku/zSTcWG6ZZocSsPXNw2v4+Y8k+eebfwtNsRy+lNIujW32Hc5vbPE9wRfvCH6QNqrAaqxBh+oZi8nI7JJJVlsXrOdV8OCi4FlxkZIxXPsqgxG1ymzspeDTayKxb9vFXy6PxlcF/kcT6cdl2YVdenxebOtiuIdxG0s8t+8p2XesdSXg/3o2fYdE+WkX0oEewuzsa+2EHWQp/2k2PuAyhwCuyzripIeGGF/BfFb+XNZPK1x/lrabfEwNJE2DLPely912s3qmH21mYfZ03C3rEpfAp/d0KL+uNZrUX2z4fJsvEfBA2o5OeEB3u/pMR/x42f0JuV1vYC8JOoz2ebZtfLHTHWiU7RMU0r7sSINCpcwejstc3sOMfAcz3kAtCCVdUEx7G3UtWhVtWE7VRBOtscIBUzpJoVhNNhhVjKolcC4D068oi3MNMb0aev/TM75bY/yV8XPaMbGhFT61oLe5O3xX5Ly5yhVm/pfps4SMw66EQSmEGX3x1/7FLh50ouOYXj4st8dOQ5q+BsDW9PB2e+Ch4s/hbL48jwGlsFtB3CdI7ecjlUnLp9Vy01FzwC+hS06Aex0/wGrHyemGZ3V5oG2eI+df/vn/258B7StIknqPJJUacjaFay4MyI/PIuVowX/AjXiWinslcqzC5sqYlzqFyKBBVLWC8aAu5f5MrOe3QPDzyfpwYezwsPj9mB/KHyXuNxe6kvh/P7LpdCH6k1Ig4U/hKcTO2IdLkrBsN6XJ0npLT3k/i8cDbIrt7PNxtYF00RcOWxyqq/orySmgQ7+f1eMm0SsaqdbTbklbmbUNnk7u1+X8+YY2SHij7ZoPASbAAQj8RFt8unFztGalZ3y94ntir98R+6SYytwmFbPxON6ljikJ44TgnDurDa9cV6k57Advmc/Ky8JAqbSt0BHsDbGnh7gYH+IJBvcbBk/75/S4XW0fmmQ/FHpBq+U/NYr5l0PGJhzw/wN7WZcFfvIJD3K3gIm5O64X2NXyt0QqH2++8Zzlfr1s0ra40HQvwGJvgOWe1a6xc8faN8yIYelZ+3pa/hOkE1YyXgLs1YfjmkSXrOjDnM7iJf7xeVm+zNtRD37Vjmic3ktSNYOWiDiYl7AoAJL98qHZ7/gY/a4eVxPicHSTmBTsGHKy/5hBjk0TI8Q//6ngijBgNuMN7NeN1p0k6oJNdbucYPQv//zfY8izDZ7uv/zz/4D6CpCw59lx37wL7ebBp+L2eH6HAw8t+/dt8fk9lokpkidTmXE62xqzYNXZXLworMBUT8pql7UJMFd00akGZiOs85RyVjDdPVaRVQqmQ4Ihb3P2XkQfpUtaS+Ml+JkLrnBbVYhcweSJiaUokoipFJ7FtcK6MmZo82kJ1HSRuCBt5wAePnWFzQvcddnb4X0vcRAsyp/x9gjvnwvR7DR+I2Hhsvgc8Lu/nha8C+t9j6A9i7MVCZDP08n1h2H9nrVvYL1LYpftjupZe94djOt1uwJB+7Dseg66dAmMbA+zTYHU78NuCQPpaVc+k49qtSXCiO9uwgA1WDPLHJoLj/ggccAdFqC1ALvmiMCTT3jmANOA2y479Nm6Wr7FEbHbGycB3eaA0+FKefl5uW+b73tYrWApkcXVbw/H2Ehf/36Tl+FbLSXrk022FBVDrZIlFViG9lQyBaZKUL7owJwV2caQavIxmKzxUZ9qdlr4K+8CvdkT7vrrbZ7V8f1cAO8tuHwN/G4D+ccC3n4dVrih8XksGsHYlYfjKvzROvaOpa9hd6aI2rcnoJFroLmEYZTtwnNnq2tQwEPoTm/svnmwd9vjw+OsMSi6yuMWL3p+Zmt122sQ/pBa6CPE5YqE/dwNngqhES8VS5UNzvNUSL1/rSv87MZOZ0djzKcH8q3WGM/OZSm541rl6E1SQFlRFiZYKrUabWzUinPosVCiE6VGxYpKuqTEjX5BS0cITYLenvGrau174ednUmsTjQIJ2B5XGW8LErGsz7h5rF3DcXXY/+E89p4NXCHt3z3hES67JUXn/kQHCWSARXka3CGgeEREv5BrDegASKDOIMV4aUfAadZXmHeb8KQ1d+V36BEK05DyI4D2D5JCGaC6JUW0Wu4fyX04UMU39RkMvUx09TZ3vaXuoNaWtNaqPOAzkKPyzaZfEAUUMfMQi1Jaa6MT7MAaBZNFBSc1BXZdZCay4rjngXsmuBAm5KJNvcLYeCe47Yk00lkFuNBpc46vH0ytBDJoFpCmT3tytu2fltjPkVz3z2u81j9U6O9a/Erg/3EZH49DTOcfA6RuQxLSrzRrV+r65Tw+NF13NlyXfHr0eXxru99fKKdz3bGG9Q7m19niAEgwqA+abU2HYT8HGJGnvR+WeChhM4ZJ29ceR7x1P2ZD23ZXHksYb6256pt/h7Y03M17WDDvRYqKq4HzHHPKltfMncb/Ol5d1EEHp40qkpRRKgyWlU/ZhVqY4sVXrl254nL9Jkm99FskBdFf9Omt4vlDYvGXz+MrfNU1MkjEyO5+Cq722H9KTr+Mw2px2C6aQO6g/iaH6B8Hq/uWv2UqPZXwCdI/oGcIs+4+t4dMp/TJKdCN5WU6eQe6051iNHRcj1SsDHbPyOhIt/zDsMEZEbnwUBog6g63RzYTXuLlRRvCKCBLnu8v290qr7qldcL1kA7xMRfkPjwT5B7bvvMRuyXvJz2CwbQa7r7R0hXpn/bwzu/5PejZ91whyvmgXKpVJFkYx9+Co/9YLaMPNkVnlQtaKs8i4zkEE3PQ3tqqs2VXZtT44hviLgTnVbL3thPyo1TwLwZDSPbzeG+bB0rC2NCBsjt++gRMPG0Pj8fP+NFv5H1dkUN9Dc6x2EaI7BF0ZrEmJ97rhpO7AcQ7l7zC4n0buILi/z18iR5NDzGV/ZL4HMWLzt386/A7IEFXDWlF4NnOThcGlyspgPc1zNH6QONTi48BP6sSyCFJPo0ZuRbxzjZngKrbdNx/0CsxUtYxTkBm3bQ52tt2U3592i6bWj7t83t5FX1g2jJlbOEwn1LyJSRphGeseJeTcdorzbTIxpnMBNRZrNBj2VkAKzmsUkNWkUuncxVFmSy1U8FnEwQTwKkwOVgruI+UORGVw3VcFlxJH3Tm8cqrSE+caGB7d/jL2Ss/R+Cbjv7pjnNJ21yAv6dV6Bbsjwe2NZGS3TNkO2wmgS/P+0F0/niw3beBK7D92/4l0m4NIy2UVls0d5Dj0a0ACc54lZSLsJvhqT6RsoJOAxbKCpAEdSS6eM4gW14e2NpuRzkVkdTW7LhpHkLy0EGFEdPrBlC/1gcxR7dK112f7mJE+/suvvld3ojkQfa8kNnpyHIOFBqOvLikkw6GFeWLIWrIMv4Pf8CS8qrakBOTORJ6ueIwmxjnsKCqraVaYIsXJmS0IJnKR1eNjQSuYKXzAKaONdtQszGA6EtcLYZHiIs/bx/CYG11z9DfKrrotkcJJyf4wLQ6vcNRu6gFtBDXaL6dPxRnH9zKizSnikc0yizpggF3F07BXVkPLsHjhpzzx13sEKIF5jNaYT57AK5qdwXibX3edh7yDXmupdbm7yD3xHb9tCows0geWo5Iu+Fv9TywqmSRIsVcgpCcRw5kFK0sSGC2UEAWaqmYxBIrGWZXcdZHllRKMlZ8+k0wgJ6FzXLdvX30oEir4UldYIIUUWpuwEW/3YHcQa7xHI4tQR125ntB6J8KPaAei4F6LJb7z806+ktxwHfXfkH/Oku74Es9u28XKCECwvlvtvllGuxuAMzE94aE8RD3291T54TN90BxKWKm4xfOdN/k5sg9ckXH6wfD1NvNhpTkjR1PV2zbGHA1SO/7Xoz5PRaVUBwWleVB2JStrjlDaRnnWVaUwJR1lsELDg2jK6sGGPS5yGBksS4VSTSQXOnSCsGcsiVZ8ESlnFAuVieh1yovVlbhGChfTLFol4NLCppNKu3kdXC5v/FL/jdprQv4vmaXPRP+zhwgPxkh7EQMVyCxW6yWtfxFaODtZW84Pcbs7tlx91D2wzHfcusGqwui2lRZE9/lpsOHLnhYrvuvQTs+7Wf7Y3qciFgTdQJie3vgeUD04OcoJW/X+BP/GQ2yWVzuDo8fd19MSO9RA/DNk1Ydd9ou/R663HsZguBhsmaQwRRhREWXeNCVCxVDyLxqJphV0UhVBMuScqmUY6U4nawukV/5y0fONppGI1PYlbbZ19PJt/RqJoV0q4jipwULPROoh0WFWu7pzbTk4+LCg7D/g6Fz/yaugPSfmpSfSPgL5XRKZm/0o4WcyHfRbgJ4GTK6G2zG1Zpo7+fExOKgqI6HptFOCw0JFstN+/mQf7vqpVXvRaP+ft+V0YVPpbnYW5r6co/XT+VX3bN5dnM3dn5e7xTxdKetEuaH3Z3veh+WLeUKiB2zTN6llr6pQM7ey82ozEAZ+VR8ZUqCRhplmTO1amGDzOCeUHquMFhaKsEkM86Y5KLmjuOjiTijNYFxHzX0npTCKcNhqhUjRFLSmxILD1IY4V2tVfhqTNYiS5ODygUfvQn38XW0SsjBfXhmts1/GaP9i1eMub8JnNfmYN2u15DF/uk9eefxIstfjpLev4lr2+1xud6HObgmnmWlvOE9ILLZbn7Fk4RtsHmYtxqSw/OQoFFgFk5c8/AyNtc3cQENQhfljIRMGfIUhmgqmBTsE5mI/RO9UqUbfAOdHPf9pg+Fbn1atd/6DeW6WrZUzsslz32W88Z+W5T9ax7Jr6dHMp0+78Cfd0cof88RKmDT2eitcTJVMOBgpTW1RKalijlrA/7hVXVeu0qlLl4KOg+sLElq0+ApSspZaG+EDiYGSvTiWhQA3lRRcvU8SWWdNMEz/B7mqgUzMKAFwWrPr4om+wNqQYlDS34nhvLcfwDK1P5Cz2QxPZMh82sSzu9VUPkDHBT9YSyHPzs/bY6/xf6plPS4COlV/PsX+B+udoXuO659E9YvlHa4BErHIbCxjmTRPV/pfCo2o0gdKepYnrf4cNxmyp0EGD6DtvVs/u1scscOUTza21s2ZtxtA8UsbvluyFM7QPA7BRJgHEYOWzB4rkwIikO6RdG61Kx1NiEpFUBzuXVUAJOy5tIwIwM3Gbiz5FZlTML2LKHAdAQfDqVUBXZspQaKFOxPp2F64gomSB9VYQF2acAnYHMansQr+Bn06IeLjH8Yoe9+wkxuwi+77eYhbylZnwgc2BJewWHX1vt6yb93gSvxbwWHYbNtjvtegjJrobN9y+CfD2UvVEe/a76Y7u58UXYz5Ai3xI3jrl3ttI1OVBOpjPMQwa4coCR6tgcFnQGsvs+PeV3IGtwCCoMhODyIFtHergv95svj9vymvjUDWApfaqqABw9MGu28KqHapBPXMapYNYdVaL3V0rkYQT95rN5Zl0AnswyvyDj0LBWKNiFrWuCJCiqGcskdRV8+FsL+0Q78ocB23/zmZ6xnMYQLv/nUf3eB63KyzspJ/MKkBUbrBGJ4pNz55v5ohzUkc/NwGLIIL2of6fpzSNkyPY7FuxQAwyvEBWYt87axqIiXSw0fWt7ue+567GXY1eBW7IUqXxHuUv301/2P93KiRJRWaOWFNCUkx5RjZP44WxRZUtzUAOspC1xQ60QKgcMCcjrWkKhehZQAEBJ1tb7C6nJgXSJywbU0UkaoiuBsNMAI567gj8RwEZVDdRa0zYlE2qp4rOALRZu9D8amhH1BmcjgpOUieg57jCuX8aEUamJVOvwO2oaZlMtrPOwqaDB6X5p6ucyzP+6n1I+X0YEf2BwbQYfP1N4gZ0RHSB0d++Ou9XmgvinfBLv7l7juErMLX3pVJuDxn8gP8Q9Hak0x+iPns+nSN5D5GD73iNW+UJ0xOSJ6MKcXygO2dO3HLVDVgtcBNO5h7BOz3AwajQBIb7DsWmFoJ3/vpO++WJAwOgkH7W3Y97Trvtr5LY6S837+1Lx7J+cX/o/5B8whCgJYFwqTsbhqa4zZcVA4L4uWwJMAqYsF6GShslRhI3GTgPtEoW0r6i/UOImK/FWVxgcqRMtRKCe8pH4yIvhcmSnRes6EApWVktyilVlB3WVsthS50DDIXPa22FKNi4xcpt54qFkKPQgiiIULZwxOi4x/FVMdr75YJjigTpdwvkSPbWnLvVZVRwYGKgIFMrBjnB9Jcl7IBJMhhlgzdfcoLOmM3eJH5HDNoL9MG2szjocEzhrAPIVRQTLta8J+k1WSDjfrRDAq0iFH4RQ8PSMJmizZgAdlocmVScobg4dXfZBBRh6sddFiuxmWYlCysojDMYsgM4iCMCb7N6gtsDGU3015wF3C7nQCXRxXdxQt/CBn1D5sNs9hv1xEOiyIutId0nWnp/P1p9M9F78RE4GSP26gog8vHbk9paVdruX+zwA68IfjKuxgorWc0NbIqSW1jL6R5Satjs0wDJ+3yzzGBE9pnr0sr1FXIqc9L62XDq2Wn5fT0fWxEMkU2g/DxsBiLrfWnU2z8TG954J5jxRHmQJXlNIpDM82ZJwjQgHNIAgOCptrp2LwXuhkbMWBgoMFlp9pLlue01U+Z99Vc5mMb2t6Mx+jwW9mVP8gQGjO+z933P+ZKleonJFEluLXKyiX7wGIjyzyRuF4Lxd9OC7pzVNW1zJTNc2ZXFF4b1isKdxOjF+WaJ8r9Sfq/XYYuDIlmYXUzqwyiCkwRkSccpXns7J+guAt/6mVmk8elS2OuSn2QLL+GmL+7gVaWtHBuP/Q7mp8KLPdcdXapwCX1NlkuUvH9f5AOJ5KzFuLuIbB024gS632lOKQZCscmy1Hj2nyB506X70Hvs7geWfwvOcD8M4Q+HvxS14ZD+DcQiVXYuKpuV80cYLgbYqpWglqYI1jUUGNOyccNYmDrjSSS2IBRsCIld5DK+osoXKhS0tkCarNe8WD8lS4rq2p4PlCUVO5XKAIBc+RmdxsL1FV5tXEhB8zKMucsIiQSpuaPHhByRn8INbCXdBJGKFwfe2MLlDBDW2ZwQCBqo0pk4NX2SJdkjABbMX1RAIjscW7IA3LPinlbAZvYMYFMCbp6OFVE0yU3klWmIf6h97OrkghCvYfK5kU0NhYGjvInOMUszXAsoEitzDlX/NODVX0z8ecm0/3Ofze4g7nyZcfdl1N7XoWzRWwW+4hxS9NkR/nDDvrR4FjB2ghSvJdD7B7V7ivFH65pgLCIWloUJL7awVONkpDPvmRyLb/QnUiG7LfKVl8G1uRyIjmWwXwYQZEtqZ67ZzsS2/qqvfB6B5eHFyfy0M54C2H7hqe/MaHOyoLbxGA3tCCDs9h+XPPW091av3V+l3SIdcjPePNvnckdYtEvBuRDUrXlFmWhmIlqtScq7YWGGUxKK6pyDfV7COQLTRMFuacwuVDwSESKCTjMuVbOM4ZTkDNEs/g4zjLApApXHW+6pDpBBPVsoq/iAzLBNQeiMWRVV8B7emB9+rFSOjtfx0qrQiTl4i9E5PfsY74uOpRnB8xA/FAHZ3Wv7XYFhUxYnsPreiTANo8LeSI60GOW8DX7EZUt1/0BZe/c4kX1finwGRL8aNSx0AZuBfO6+mqUzrgKToz9NNcL/dUT4Lf9x/3oq0hVLSn1JwjdZfaUQFJWK6Ou/LRUsnTzlpgp90yMaHz4OrdcZ75B9LcoUqlqqH6WMDFhRXApWaWNK/VSlSY76LwIHKVzofkQ60JqjlpAQVvAulVXYuPHjY2BwnIJirpreLSOBjJMO1hnBcnNWBcCuzhEGyFpY/PhSIUfZE4ho/ahqpUrk5RuUqJEicBVDUlZKToNHfQ7L5mxWT2YDMsg2KAYJAPkFPqRvIlO2j15GKSHm+JMx+EAyWwHNcF50lQ+jg9arLFGQ9WYyUsG+e00UqyaxOkh2wn4Rq8yN/W6PZ2GtePA+YmbYv1cX9YxLI4OaxbX7ZeFbxYLQ90Fn0bpD+40C1gX7rr2wlLECxdxw1fnrXYSQsJkcL90wTrIUDcMxO6O34MIYXVfjv0MGxR27FTwNh6+kaldPkzvaOxRQDp0T+T72A/9cEaltt/PNNxvJH2xLC3bc8xoy49Vw2km8i+n6U/v0gqfsvN+PbB4aCDBQBukkgxAGtAfY2ykPvOM05JUiE5g8+AX1Myf9EcHD1B8TNdfMtKjfhfZkwIQKMuxgPDsDqEd1xHLazWMccsYXc4DzujuswjNQGBEeRBFOhepPTSA+kqp4jVYbkEnqlyRxnuK5gC8Qwngy0CHMTaKBgISSoeZoGKnm6ZqZCs1DZShx5uI0UpjACpULpgw1nh6KAEMi1D5oGxVKJRIuMegyfGQZco2jiYNtLinLT4NlW2qmp4JVcpTypIqyJMmFyYKdKAkcUScLTB7CjdRMosUL89nMKm4imQS5bj4zjoBM5Iweg0xbGXuaK4SYw4B1XCToOrEQccHfoZH7aCFdg+BTYOSJVWpTAYVdThO9QgYdVgCcarMlZoD5sQxzpMHuEtTLO3TsDFcPDNfxlg8DOFIq/Ot6HTCA4eHAyg80SvDqvn73GivXHpqzPsfz5FAzu0T5nMQ1uG1BKklxQlWYfNph05ZfZY8PB3zRgZasz/1expVcI+0DGAs6s8bnuNRG+pUHpsckX13rv9Y2vgBe1LaaY4uB6Pu0M7n8YTlZwVeF3h4e04/LDZ/rVIBfTbbhel9uge6NxsRtAY1Jm8JTGswtC5c3z1U2vw4Yyjoqbxjrr0vWeOdMrDO+V54S95hwDBLLGSu8hjEbECUzjJpKnUGlMlz4DsaEuIlgKaOEiMlyANPFWRtHTCNexqOnuYC6XKEmNK4BjJU/RfMhlDkA6nljNa04FEjTVxair8S4P/4NBocRJq3le4DEXi1MN5gVVxGFlOBxcWDTXitFAwpbThCUceDKFsnDPVGtFy/EGNgonFFJxGPoO+WSW5wmGLk0dlK3FPzEVsz4nAsDEVIr4rXWEJq7Y4ccBpwqKDTcZwVhZVc4iRnLTFS2VKMDi2LEVYM89KpixgyRnNcy7CwDaT73AoaoDT4Psznh1PR8oRJaOj9dBfUaRzZOffxcy5c4Grc+QfDr1/7ZWtQ5UZQ2/LbtNMDc6pi+xVgcd8tt9218Rg3lD1BOVyP4JtUD4oZbRN59WbQdJlO6iIPb3W1IhIDRGYMfm7cZdx+1dL3Qn/O32hTmSZFWQ7EbHgWgLNPAqK1BXPDZdaF22FlAJSrcAeBPQ8lHo1QFS15AstRalaQI4iA8yzU8l6oKI2SoKfal9xJQV+YT0T0egomVA1CQZmAX1/GyDtpZ/n9b6sEfkZEdPt9v2SPCvNUg+xNYVevt0i96OOgXcXeCOcMTV8CRcRiqGv3il8Adr98Cv5/btyOwfbQ2tw+wXb31Me6C5MBRKF6HlIz/PZcrU6Uorv4aohzL8e9jv793gBgVpr7nbDdJxNn3czAJI8D5Qg/HZrilMbiyFDoaHvcHa/k7fqLF2h5Csvw3zMQLq1xdahcmqce7qxu8yPk9+w/dEdFuK9TAYwY+cclVslMBeCmhUO9DpZmAkZINZccvIfspgT1eAbZkurT0wJtj6t6RNXzMoKWu1C1ND3RehgAzAqRTAu58Q51ePzElMJijwCsF4cdKqRVROViE7XAC5flfXQhcXihHAhZCkyCAS2JKLFBaThJtWIEwV/xRmnMkh4roKg5b0S2kJ7UtVkLdTAt/osivcWCtgn/NdIaOJqleKiRgdVrUWQXFPklL3iopiE/qm9IYJweFhu21N8vsgqeNp+uTpKTp9cpkvQ/Fw5BdOZc1Xb0fyDYb2n7kD7fsQ+L3qi67cdPR9b51pnj58EhB5KT5dtwYLvXWRyXl1y6MN61lucLst1v8zQQKDVv1BGQ88Abs6E6SgZJgb1o+8tm4CuMT2D6QC7qjg5ZTP2QUXTMn0X9zTGEZ3mi3eHO6jqFBnaVtviQHeLAvmF6cudNeSlJMemzhzmsQaauU2SgQ1wW4URuhnlADB1QLQ2Vg8LWmcP+yAYC1KfawLUNf4ACcg+VZdhRWscOQE0Q4FIU/T0CrD94byo8pj/cqX8W6fZT5vtl1WhWQh/W97GAp2xpjZukIRCrdwKGA7OpuflWCXWIqitM2Iu8TCgixqSpZsl1Jq/QO1ba9wqCXtnxXsYRD62Popj6wEK7+E5Ab94BPSb+YyCj0NRF0V8CsEY4H6kZoFDmk/HdZ++BRN414o/Q4vNrVtzjrbRWRsm9BSex6jFqT3dNq6WD30e1ztTu9Jx16q9z77xdpOQE23Jy9om6x36dv6YwESy1nkPEClYxCJSrEADYVyJYjSIvC/GSieTh24HQ6AEB4A8Zliv4OuOXnPUmcIBhvvMlRMRBIEzWzVYPYx7V4SAlW6zIx3vAGzPcCRQtNJn5bInz14wYPImGWurV06JQIVeunXpcWBmpnL8R1RY6zGoqKG8ZfTCM15g33NHlyimSpwuOSuTHX5jwTSiETAkJHkXLdbDTXHuXWTW5gg2IhRlZjrBKn57eYg8QbIeqcUh/jNmGkzC1o6OUWrb6LI7u0u+3Vm8+6B3z4uppecPo/jfPEyo5qSXdIdWT9lthOFh0SO4Pfns286TOxe9HudE2pMU75D1N3y5K+jt/vBrLoEqxOnrveECsYewgzj08rT9I94u9MmtSlOqzDnSVYewxDh57IH07eGYy4tT6+1uXBcn3flOp+9ftewbWzIMT/XuIMXbJ0SVEaTe5SCkKxpGewRVTpILK5JOjGIQVGAAQ19xbUSuVZBp7wC5knJojBzWPqi6UY5nzcDbQzIymGBpRoekXMXmDuM0yhbmQxKU5Wxh0cuQE5jFNTbbo7hG5PBmSD33F/Y3kr/4Jvb2nyjHsHX2bk1FF+NjWKxh0I5pF98Ze3cu+oY6D2miXd3+3cbfe+1VJ9AwqfYtdWZLKrAPn20Nu/p8jNXzjMZRkEeu125/2s8ewY1b5/E0OPjJu3U4wwoVqBFeNtvmZyBSMazSx2/s3+jb3+3+ftstI2na7fZ0JLxU6zgIVnhOB2oom/PujuSCKVT4Tk/lWjPMZ3BopmC06yBSoPZAlKwTjDTK+FKCC2Sdw24WziajDVUZRXyDNbbFmTHkAS/WMZtCrJyKi/DTqr0iHs+8LUGGUG2I2TtTrIS5TTa3Ttpe94ad0HeSjjOEDify3V2Yf2TMDZvF/jd9IhRkBWZGee6TDxbD2KPvj7sPLPyiJ1773K+9p/44l2m5nzxMJKlhqKQ5d9HFslqWOoASD75QFj55tHCENi/3CM/UyPWs7W345ZCs97k8Dy7yCYojyz3CsC6b2WCbhoeyAV//YP/zqQPtjRs8u7Fx8dOW726H8pFyICGZcxVsOTvHFUiw5cUXApIAoKBEM6nNoCjBlv5U1ilGRi6Qy7vjTmTjnaMsvlRCpBE3UtYSE2xoLj1XhRsbEpMlcFBtatfMWLG5qEw9xlpYLnpAJ5MTTlTDTBbRhexJ5brEqBhJWxVFYjpy76WqifnCU4UWlq7a1qIlwcIu1UbPizDG8URJvtZZC72fQc1hHSgXcRqADcASiNiSkAHWgolY0rlXj4cXHG2Q6lF47zwi7jDBfzLn2tt6ftSw033UQJ2TWnvM4+oPMNjvWfGGhh+nN+blfhodcg6/Tq2vK9tPFLn1MKOFxng6TpC0oz6Z4ynRFe+NtKS6Xa22X8ZkYywXIs0NaSPmtqnk41VW0TQMcrmm7p7L/TvdXW7lDo1VEkNXppN50D1+4y2eNvDiWXxrTZBIVKfLoe9hKlsN5sxkzoRGrnmJsO4NcemigzT4v1QUddd1OGOEoPEjrwK1vYUTPod3Pr2pvxF2/bTd/h6Wv+WwXD1Dwtf0x9Px93CWYzL1FrsJMvECZP2SV3C6e4ErTP2vrSIGH6WMk1XLOIGWHHJHeq16n27VGjFMifVtOQqX0bz4ea93W1aaGUnZgKSpI/W27TbtkjrRTu3caajrdvdp1qzk9bJ3Uw+vO7r+7vbkg2nHdLPTqmUFi2HXJuzMTwqdumBnPMPLbfdy/uP+7GIf9oG94/yiFpyZSRGlVwpa1nIbwL4rRapzSkrb5CP0YqFKWZWNFqLIqgPFjEwzoKVSlLBCeShZySAZ9HzJOufCebGVO0reSF7bmJm2tjrQaqdFcK1guJC2lqyaKjznLnseWOJGKahmrFBS1Jk54DR4kZ3gVlLSnmTFaV1lMdmofO25wuMmYIyP7OT97iI4tUn7m8Jv99c996EUg/w0VdX8zoNv+Fvwe/cC1/0vzr43Cfa1+mvj50hx/cMjbnA++7vyeTmf/SPNrjnOZ/8m4Lk8hu60/ofj7jlMBHoTWuXCOKCo26U01aTVOkzxn5MneVceRrdUG9T4dpbJfnax/YZk2kSP1g833YzqXoFLTcaGBLQ+jIemb93ITSllrNpv7dKudp+269bihkocX+z87j4cbyMfnNdzKpqBCRxlZlZKLpOTXHEeAuDmAFsvjIuR6Zwk05UmFGlmpHQq0PkCam2lpsx3V0qtmiVLyfg1cGqRUckJHqP2WYiQLKtSqOpNtTQqwtR4HWY+l6/mzeoDjDIkgZzMTRRI/XZZoE+QINzLlr+mWOYHAfZ211KvFl1LLS5weNby8euBfe8Cb7izJhY4xH9vgn6wkFtRUzrMZ+PCQ3/5yaYeSmE24NHUFZ5Mm7AaQlYTsPdtbPQO0vGZ5hPRV6axR503h5EMN2iOdbH/cIy78Ni6Or5lZtNeX0Ifuz9tsz2u52ExiN7nsjpPQD2V676aGDNteLm5+cTubtl9M7v+HQcaCHJSjgrnlNOwyqHlocipd4dLWhWYsrpC1aZkBQONNlIk56GPPeh1crRmsbB7bZbKF+kppZxJboySicFux1FYWHC2JKnoPJDB+pgEyzCQswv4FxnZ0krW4mLa6uCUtCGCghSodpeCrDLXFCltPNgYQfFtDEFT2ZBNRDYinULKwk6PMmZVgqnK0KhOL4qHqe7BGJIPRWWGU4nKf73GlnEDOsXMsT1t2yWKZ0WTRx62A+gH1i+gQUmpbBV+XDhRj0JzoSSIB51shcvqvZMiSF/fPMgGOnI+O+okgn/7xxd1Sy2519VNplMrv6mgidQ97mGbv+X4unuBq+Pr/xq+1wyK7iM7meKlT9A4eem7UU3tTSnr/ZR0MuSfNj5BLcsbF3hY1j7iogexP7fejVRJE/ZjnQ31QO7bo8b9HxxKQ+bFeNvdNBm7Iy/3k3uv7zTStExYHb3/3WU94lTzexGju7tL6vwe41xHnC2hwgKn7hw8JVa5hLVO/rLqbe3WhFbgHoLH5CUM+EBHiHPVs0gvLpTAQlTaCe9hTlhhiy7C5cC5dSA63CTqKFnozHLSKpwjMF2q9DIknr1qdTNcWW94SAlf4uAmImMhy4wqvGqDpxQTdkTGTVKlzcqJzGucczF7czVxYHz0F86AAej3+vdbORXhdXT7NYk9laL9MG6BJr2LsXEV9TwdlNMTTdtYwwj/JqfAfZe/wTz6N190z0nhqeWpQ6Jba7yW15IoBbwFy0azAWdvm3pbUk+WbSuRwT/Sje5HaMGBPfhDL7+jNN2+u4956EcX/LDn8W57zc3pfvsu3u/S8TbiqLzWSUMdijNVfyRAJkTBPH4AlSVyNtF7aXRUxoGUe+VzgoLMjr4VrsJa6+OuzRq9elEfFfcfysk1npAX3RtJGo7rp1eTxT/k5bpnhRdDaR6GFk/TAf6FTn+qw2w9RcEXbw2lob4Lx17SPa7VRqKdFhsTKKbLfWnx4WnoMwWJaXggLftOq8junZo2OPqfKeT9cErsbK3uHkNcDtka6XF7xyxP/p7FyktWVUF8OXV8Cg4cLRlmLIV8k7EKRzlnSsRUFc5yxakestYksgJzlcLe9BK1DMiLJvmXr2k66+93Fr3T1fGvj4WARQJx0fVvNEL4U/tNc+V8poTABbU/epmC9RIS8iUkTpe+Llv8wEJv2JnTh/czvLme4PsfpkvPqFlLoRET1JjxaUmNf4fkY0pu/rRcrYY8x2aDHppKaKZjz4Q8uWxDG+Y59WgbMpHOYyfDMN4xDQL6pl/jvT4q782wPrsb6swbHt6/nyWVaK7CmI7R93FXy6fXMibn75dwv+NXFhK2olcCpp53UUDThMpychrGIZUjUmc2asTomZLaO58lfk61DQkfax0df4SMSDJQTTS8NZlVnLmEz5QkwA9FiTxoBzqbcNx47QzuhjnjLIhldNUWFl0LJNvii9YCxjT1gxQZC9YgizfeKVPxhLDNGC3MUq4CucxhuVZpTMSGqRcNVW2aamMtsNAbQ63eFeFFNULyEK1TOSZlQZGNC5ImGGuNDUeG6+sKnkyPszLlcEua4dmpnBhMZBt85LlQwbvmNKqgagfbOlK7SpjXnsrVMgz0QjFvGjPJcqwuJvLnp8yl8azCRjcRx7ILAl8W3tiqYpWBeZcK/h9vpKhUrMbTICLuo7I1moz3J/AeVYQtXSkMkKnPFo9VqaDpIM8KglF1K2ONRYHP4H+uzvDToTKmoZ418jtDzDj65HTKnJ/mr2ed/oGNeH4gHYDTLFPp57aCtmFXYbOBybYJi316xKa++ei/4/ovknXOgmejjXpeyD3Vy1HV96zHFKEQmuN/mVs7ytbasvMVmtl4oIOTOvcuhyZaLVtmqkdtQ43Kr4loFXnih9J4fOfT8oBtbnp+D5ns4yQl7IEK3N803U9DmcabnvWbvqEChptrMb+7w33vuvm4Mxp2dJTAa43UrY7huElZuihZVLC7OcyFCqaUampdsWLryRd9MDWU63ayw11c5H/3ZzcUm7SH9jNVkZ4j4QnGzjjrp9GUMT/yzaqQj2DhrhWuU7YnWaSo9Ckr+wuZqlSV1R7hft4dPtQ4s51PbRplfzfjlJ3uQsfZVM4STIeFX+Zzt72OTTQbSoaU0v1YVjL4vqdu2OVh2135rS5tzEOBqO/eRAmV6zd32biVW/yoRdd6kdjFzs7KSF/c0lUR2ONxvZwI1Hkl1Psur3daYJsSAgcpUAI6uMhQpWOeU1sqFagGjHlvYmGZSehK6FaddBFaOls0NLy/tkxOMnKOqgshXB4O1M+ZKpIJBcOdXdZcfr/+cD+RRTM8JOo420udyC989sPXvM0fQfGda1xXY9IHqBCqGRFjp/jriUCbk3k9WPxfhmEQffbdrjzAmO8fXofNslKa1+SCPjmcv26m7IgcLH3RFnqoojz9Fht7v1nK26ghf6wC54SyqZyKra0RUeQM20AkmAEKyl3SDJ8M1kq811OnVWM0+bRkvs7bmsBxw1U1vcmPTr786xccl89h+UxD41ZEmWL49Kn3PBikDYL3uHzAEz0sWn0fVQQdjpvbmkq9rDq+fflX5P2txV4I+6q2EZOjzAwDq8C6mntouaZhb2RbD+ztxmisQm1OqWIXL3RVHppTtxcxUqRlTglcmxaYeTGqrncHoXTGfR3SJc9t995ivbVjHhdradvDR9twykI+s4+lQlIhxXS/5GgbADk8s2HvkR5LT78eIsWQl576OTaGS83c2DzP+oE8XvN7zd8SKRaY4xTKjEVmWFlChwirTNrAYHu6ACoIIzJTNqUwyicPGzEoGI5WSvIO8GhhOGptRGBM4l8SJiUsxWSZr2THW/yOLDeWhIvUqi0nnwjIVjCWzWvQ3Q9SM04nulBzH5ic8sPDtg9y633RW55DL98b3Obgeav8hyD4znVfMtBhSlRrwDFIeIub0uXG4oZ2PcLf/DTJecpabtf+vCxfRlQM9zHvQ1qbkhnOCPrtWN3UvjaFbc4Silvq8NcNteu7bstQt+Rz5jns4LxU+v05XneVGVujdNBOVCmoQYh1JbpoknGOxWCr5pYahINISppQVxg163BaOZmhH11rIFgJTNCaxlkTrA6ApwjaRyDUecEK9zxF7VX21OUreWrPJS1VNjDBQUOvbTl6X4uxzd65RddfGYU3qWfH/u4wz6p37IfFu4B1sN62uOZP09rjFcim7YoczWS0jiiaboZE7mHXPUzfD6x3r3gF03+3e8BL/ScKWZ4g+rQLS3KZkFJbUiFB2E+xpSEhq+ubXikwn7VKAML0AzD31JMb98f9oedHxOerriHn4ymHrOz5oIPH1MXOGPtGZm0b++Pq7UrD/3Ikxx353G9nP7QyxkL9/9uNnZ7YvbryvWCT5yJbq2sGhLxKpvrotbCmGGrTpXQplUtpJY1qjtQ1PPhifakqlCRFUK9puG1/R6PUX7zO/vQuwPYz8M9YDiTix31rmb8qy/1x94fxz1cXu8LC/9l/Q32ten+tC0hc8MzWzBfyXIdwylhBsCuElrEkd3MeUj05CtufhI31G8Wzr9lc69YPZ9xZM7Gmpl6n1e/OAnwnLyAmx4WG5GpbvK3WcK8MS0ZZHlMqKUN2YWixVL323CfpSbFUk5NzvvaEX5Up1JKKq0XQoEnwO1zWwSjzBXotaicr+GMpguviocmqEJk56pYvX7SpmUBxeo2/b38q5+Fr6PhEs+03LSVtja013zeNamkdFt9wJX4tQO5c7woj/0f/1k1I4CLdy75dtyEzTS8cerBzfjZCr02XKQf880ztkFTT9kidTJ3bWlbCYym7sf3icYP3sydjiPrQ3TOpctxwS8vpzpLy59A8nGcc7iqRGCJ1tkuSjvcA9V7teWZeJuro5KQFQHxxKVNuDSickcxbST52qoNxySTGXcUvVK0+BR+jqlflKsO7uyBgp71SLetjeID8wRA6NU571Y3xciL3q63XfnjdMo4VfjrG1kTg+Q9RKjdXueW668rjuHsYJIuGCZPBitcHwDTyASoy9DwlVjJdcUhdn2Uwl/GbkGECwplaOvNHTO3KKL+cWuZ8TYZo60xx2sTQyW1Vf21xTnJInNTi3aXg7w15yCJrJRIs/eJlZTBQqiu21hoAisiqszVwGmuoqZE6ZC9mHnOypgIYLdQNhGhoJGmYo2bJ1QcuK/RTcTTVieY+pliMp+GPKdocdKIRyZYZzTK/7pTyqmvhpsf8J9U2j2X1RMlmgy96uR9zKL8rXt5c5Qov/0+zMUJLZllT8HUX1j05Z35RDQGrppVy0LUp3yY3TnXb+TxWkTT3eP/UG5nTb7dKuNjXYfvC/d1KvO6qwXiRDj2/J0cTNCqYXIh+ORj92ZXcJqRxcC6bdbKF8VSMk4qZkFR1NJs0UGt9agrYph9nnYWzQUrYIpkyOKPL1luRvVTRFqV9ZDBZAgduMqNOwqZ4XawJVAbdyh6MNslyyalLSsAODPUUB2DxWxcLzJuoRKF5JiZWyhRlmUaSl0yRYp4T3WtwqtCoUkcjBnLhpP24p2nKTtFecHdVmWy1r8YEXch94YrGrVP6CWcv8znG13KhD88k7TSw/L4cjp+kU2FYHJ+XsA1hgSzwy93xCf/99Ama/zeAc//4OWSgtDvrxpZ6i142uOjZaTfBrm81QHh9rSvIf2DlN3L28C0oMqKVm3LohdX1rC/g4B+8bPY19TI862/Y2xp2XXpxPtD408NuOwSh//G0aVKlkx+ecitO/Qunyajv1X9eXK5VfpbdOIbx0HJn++Tn0w2dclf6Pb3vtn/HcyidAe68kclVxsmUMoToYorNOBkcNKfSOmRq6q+DFsUXRb1FC5VZa36JsbN3ejZD8LyPWH/OzZ33+XTg3+cD/CEAM9rQi1MJOAWMFq26f09D/Tbdbb2gGPsfgJuPb+CFJ2/wApxlpJJ761RufFHJs9wU/CpEsEVagoTwuNlsSb6Hcb/XKnU+696FpqX7QDFyp/UxqF+ovRzF7hprPQBB6zc7gz2/LHMk/rl9eROtQupqt9RnkBo33Nzne9h5O3H1nXbfNrGieJJFSh8lA28t1ZRsOfdQqlxSLCzil0bFbLIOwkRjaaS4sDkGcrtYZbNnNKWi6hoNVz5r/CxYpqDOEw8lUk66t6FCbxeKhzENKttyRsFyybpTujKYjt7iUtyCyMoigrQJpEDj04amHRcdwaONxC5zqLEKYF0ITwNGW/sEJok0Q9PDCpWauhFrpWChqkoUg0uFbXuQZ8ZS5EowhkviXoOz1LyYLoGdMmV0ESIwK3ikLNSYgtDWJ6+zVUpmWwKjy0bqCUEJvJVXTZOY7GsjS2/0YLgW/rst2R9DF5+PcyR3C5kUOCToVk4FAN9bDd+16H3jSMFtNodfY+ghgW2eDck+rbrp83ZFMwbCbEUN3HHGPOzK4FoBKSNHagdpn0gW+sCOZrbuzyeLTimbZMn2zLNmHNNsgcPhc/gYZz+NGL14DuchxjYlcWQWXfi+U5tBatYZhVYu+JCjTsE4L2JiYNtM6RSN91ZpTjE8/FInWTMLVSSgTirTJof5AsRRQ7AkbAoOqIwqgI0r55iknO8U8H1GQwppqo70QoAwe036nkO5X6nvq3mip+nAy0LOov6EL2MIp1rDO2Nx8cSRL3PBboTaX5sd+kPAtbUmOR1CQ6bkMNn3DyYBH1r7Crz/G17PfEjw/Exgp/YH+y+lPDWnawPuWSP7zokfdss+NqS5XwcX6eAfbclhx034vF3mVh95k1gcxqDgcvN7C560JOrGFPBPbKG5uUbaMBD3PvZwf9lZLJfNso9rbwkw4fUx6Y1n30dzhkfYb2V8hO3i84GaT0wE11yTmO2+k2OLChJ8osCHgSHLIkxsUzTNHJUaTNvEpLiBAk2RJQ0jXXtHTQtVzlEG3aeXRmpToKG1rRDKs6B19NGYrGyElc+1rsqLoCTOiMwdx4+UlFDTDN/n1zT+LRV7TvF/MvV6bnDuFxP37H2GhnL+wR75g83d91e/wuy5oXgjqxOC3e1eCkhOo7zHHgAZgO8TcoYG2YS7Vdjvu7gPfrBQhzk68fkVML+LtKfjrlUZ3NCz+/3yoReQne7kWzOjpdJRcy+YoKwysFJy2FprjecqxCI4dCWoq/YCQp6LgNakMdya6q9crekt23V6P5Qa05/j6w6iN3vSv5FL9kPA4qwXfzPYSTqHbutUnPT2lKtvw8RHlr7BQFt3qwdSIMMIh5dlBm0UfZ8ue7rwWVoJxSCb6wZ3QPsc+mlSiHK3GSzK/WwV1u2Kbwp/2JVTz63LXZ2rjwtY9AvT15bEiBNt6Vszn2HC0TRUmwwPkRVbYE9qmtEIqJDBp61UXpFZJ7KsljORUw7kiaVhMvL1SQ2jO+f8tYzSPnTnPzz/UT1nfgyoDLbHghKcKEhBMWbKJGxxvgXNJdrt+9yE7dBB+o9QJV+7jSsI/cfmbCRlcD55hfzizWFHXI3aypy3peoBljFA38KVlER1yvla7tJxvT/0C+Br6+VhquOhRJahe0AidJ1Tuqt8rqamsPcD7ak7Oj8Yowz5MyWEtfKGaSbUcEfD7VDbzt3zRT/u0+1/a9/YxFiyqaZEGV1J6ATdVJNnXJeaYlSaSW8Lrz1FmsqUQ9DR+pxkhKl2RcjOGqVNROyk7O8OM/6FQHSRWf3p03GxX0K4SWRwxFOvPRwlG8j5b80EmMaP7emq7Shph23zat5Ej3mBnntXvI7S37X+dbh+fQmZydlPXGp9bGZLCsNk0iHHfjBjlnEoEbtWU2dD0E9VnQ/HJSyUnoIIO3i0jYYNkuKYX2Con6D0kc32c6Fx7QWvsey/tuXy/upGx+ln0I8NObkNdq/fq3JAB04mi5PCheK5z9FG/N1l2DwEDM8BJxmT8TUopbitvkqZvbAwbFLzmDJZVOEpW65irrEW5r3XIuPj1WgTDA1tp4aTNAmdB9haLopoqozQg7Jep5CdS8eV3jt7Ca/Wpn6vErkfDbVdxhdhmamj0tBzmZoYrbeb10KF3w2ydyx+zRTPzvcBntRZJuy2R+JlJeces6jH9tSHGOBQOISXn8eesuRq3IXnaSjhUAlL4YTjLlMVd9d0lwWqNFl1N9UYDFHnjzkpT+PLXrmVIUa4amf90BZnEMk7QoR31hhkF2Fu2UIldMyCPbpSDaCG/xclJltLBNkM3lXnpavcVc9LDSGKamLVpLIsDw5GZa00ZDhpB2RL74mvRsIrcwBlEjELx8BTQ3ZQnYVnqRJNRGXmunvUKAqtnTq9r4u4/usFPn+h4tUfDbgQosMSYkduQqrrhIlVS+jh2D8Qsm8ue93PmVLHlg/lV9JcTTtCFLvDrgk5ISrUujqWYVIoHcS7lsQ2TB/tTaPGiHwLPPaKoW6cEY2FPqUtpVbNQBPITuV5YXWmtlvbK6oV+nw12WAE+Acr+IatTrfUZoaf31AvJO+pUDhuWqXgAOrvNG3M1piYB+EMFN6PPAUq6tEGWPRgpFkyzh1zNO5EVwubUPNsrYyG4x+ydVWFBq0eHy7R+ySoipbml0HZpmCr5Kw4VovwlmWeRQ2FK1lj0CwUlys+fwniLyWs2hyEAWHpCDQMHvOhdKHLzFXlwitw/OvGC+5G4nVjhgUuiI+SCXfYLhq72m7+YPJ7/x5euF4IW2OqaW91QlC8HJxAVy3nM8AmFdho5SmFIKTDpcoCq6QpBvOhC8tLsnyWv/o5rI7NSznNFiX4vGkrTp88Tyif7r3PcqD9b9el9bM7v8/vFPgDBbWyBOO9EypEaXLNAJBgVgQXXQg1SOUDpXtbHzlTBaSXQnlBCGXbKlGWit9k6MqYecU3heeK5nJ7HYWhqlmncnEhm+KEMIJlKqcwnLpm+ehey2SdpKK9gwscvq5Pv6Fl3Q9nko5g2ORFfAyfDsvFMFp6sV6Sp367o0bA6Y+2TD+yjTcLaoey89+3rcKuzyson7fjlJ+r2owvoY31wiVJxfXJX8umEHvc67rJaA8NBmqH0sv9diVtH1qd4Df1iJhPmxyHhTfreknlv63eou+jLf1+FO6d2iXLQF+pCVyOWVtqsSJEqNzSHC/pfHKgptQDLqaiswD1VYzVpMBXs3Mivgal/t5uNFTpL+6DzSJ+BBR9OmKj6+N68XDc0J+/Tfs+G7fTfOlLrAMZ6J2yt3jytyvO7Qu8XC9x3enxYwteIePvT76MUwTgbNRVy/KIVLzQ/IZDL67T7Pgmep+3q+OGsiTa2Mnt04FSNc/p4TaW5x7ExjshB8lQn7R/xntoxX9fduTZpFyW7eMyDj2+uwosu/ThKVlAY6VY/tnG2jPZEAGifmONUw2p6HQjh2kHNHbqO0/9obmYtTcvlEynCs0kRUmgnCl64ymGLXwWsA+NEA6kUTJhASZpUvWpyjZKB5+rPCufM6vGOerLHYA4KMwE/UV+ocTxL2A0UjCbmRhllZo7qiuk/RpYodxQkiqvVUvwWaVjsEqbalRSvLXbx8KWMuWUcDmDpyqVXJu/ez1g79z1c9HPdXzmz+ezLAZ2Sppw/6ESkL+i9+cFtDs9g4raHSCIC6pjbZPtFjWAZO+/D5zvWORG3O8q/jCqnFZe2753Im0Bv+i+GBp2RU0baEj44JtZj0PwclktI8GU+nC3PTX8bvLEaVsDMmKGnb0OGyYDszVcerNXxNB4hchk9wMPHS16q6azrsbD5ptOpSScqU79O03lETIJKpTIYKg0uY7SMI2SLGYhotS+Vic5KGlgrlBzz5CygJ3HvdWKuZZvJsAuM0AlASNbSzGOckVTdqaYCGOxcGeyZrYmJm3NwJinHhPQqtSexV15cKa3PDxPAsFTKenxvlD7Xym88QIqabujBItFF4WmkXskrr3AMy/Sd0DM/Wu9YIXti0M74UvpO9eBsYzVg3TtqT/YEFDbzR4vwxVTj4H5rKnIqW53tfwEVD2SHI85JrDNwi7/qw6ZLxSeo4F5oXtZSRmV/bLHDl/Xf/jY7YLEZSuoCE8kAbvW+6npu3bTV7f7fs37O4QxOcegPTxZWTWrGmMKoI1VVcFpBqz1JeRcNYOqilVWbqQHYTQgltJfj6ZK04sZO4ZTWh3kY/gRPfgPzZN72j+nx1dyLP9qGOkNOk6OVtKiYChjAOXbgfHOAi/8jK1fyPWkuEHyyTF3fvL342kWqeJ1S8LYnYMUGaKPN4xQvU4peU99KufNXjpz1vd32IIGvYsNJGmITVNDILKIpklsA+sctAZF33uTlY9xQoLE0BTldKWWt0mxyTaA5m5nxvyr5zVDzaQAfAQjdeUsa2Oy4dR3W9MAleiki5laMHtTtGeFqWw5gMJMriqH1NpCVCUltZKAEgK3qzRmyVEetOOBxjUKyomMuRjOfOC2RGml5V54qTVLtFFLHg9ZoSdBA21wXvMkdak1ScoOK8rW4BMTkqIR+Ga2qTJdldUyJ2hJiizGIhwpycB04CJ7RdMChGBBeeGkopbhNPHJU7Np1SbTUZPqlEMJXCvZ5kDFoCQvKsDS9CpJ6NrkhMKmcM9M5iIih3KtUanIWeAJT4uVYHE9l61tbbapvSfDzqmnIVfYpQk1gsNCs5dcnZDaZY/zCJqcZlMJrmDIqmyqVjSs5jqpAOJBncwftvTf0X03QOb9fgB/Lf27jWH9Wy+Fbw4Smg+x6+0pyPeLA2/9WhzSvTxW6GrXczbuufbVifJ3vTS/W4kPNIztRcvbsNz1Kqg0FUwc94+n9JRxlMZuu3loSTVD4GK83nJorkQ6sK9GE5ni/rA7psPXOlzy1b6/UzSfm5wshRmYb9UMQCYvVsCU4yF5qiPOUoTEss+hBkYTGxNzEHYcFNK3ImQjs/YiCStooFJSFhS0Ks1aeqfQNkRdcAREayvsuSAYwAvl7YtRNVgvL6W932erRsRdkrxDqlIrSVwewkd6XvwQ+rVhoAsnqaE9zCYS2AeyRJs0fYP4v3fZ64bqTTyvA+Qty38MgrcrnJs6cZvBGLs/7/djfujZLN2z99BiAM3aGjXrcj+bUvLJN3/YgV1OLvqy2pePa8eOqnaXL/Y4W2/3h/fj5m9DICYXIuReQz5d4RmHfeQ6xOig66jFHrWbELCfuBE+eCuotAdiLKB2WLwe/DeKLT0zci7iAY588UWp22MLqr3awPLHEeDhoH3Ybb/sF/SyF/UVT+GHDu6X17t9WC/3Y5+swTNely2JFydzu0SXP1ziT63X+ZaaAFw2fn1oCReD15wKW78Qw9qFz+30Jr533EWyaOZUQVPq/HTQviWxnZcud+XW/lpdGm29P4/3nQPv5HVYxXnR1CvcKpzaomabowPR8RFiCfslU14VDJ3oWyUZTH6bhKdJYF5X9soxOzyEswN3mEV3Iak/jii213Op8g9ftosWLaTMhbrrnaaoMcF0j18ppl+11pUI/5tpwPyJblzYMrjiVD7VBnydrjoIF8wUejI9xwL2TGzmfjOU6ViFOUONFdpku+1QRDIstj0e3upgfJtxtFyG0nFwtnFc+7gZOuRNW/vmDoshVVmYVNpF5SiaA1aRTMk0F8dnA2PBVPyKxrKqSCPm8UE6gXFQs5TrK0Ld9n7OIdbbFwz5TZGev9pM5C8q7GODojbW9Ig3uQgPYbnZHxbjnX2taN9x5Rez6dZlHXtT+rGB9/bL5twbSqMLe+44PkAqrw03fOlAvUw/X3bX8HrdecP5UNI2072WtsHZsMH3TuWLiSswoVeDN+2WoA+rDs2+h94hd9Hre/st2mi1YErZ4ohIgzqbGCMjy684UWlIVXZgH8pRqb0tioYyqVpq0cqX1EYba1jaiYqCYV7SpCURtAEBZyDXJsLgrtUZr7EItfIuCSzdgV4HGNym+Hibnkytr276sn5gpy7J8uLTlsowQAAesNJygbPw+NuXsliF9IlIxXGIvLc72y0fHg+F6pRex4y/jZlb61zh6AOrvtEd57w4/9R5Y1svgAaZpkxS6ik3OrfObNAe/lzTkMne4G3awXR+N6t1cFt9edyCU3+mzvs4zqmwo8dV932eMQzVjzP1L+S56vk+9Ex6VkJrKzK6nHtrka4HD7dOhtP9fCf7lnHuffPESO+d8zKZHLhgifqfJm6Ds8HLGqvVzGkD8Bkja00tU9ZJ8ua4ykTMWipoJOqqA3vXJCFliMkzXyX14AqCrFvjrYNVC7MBJoRW1DnYcXMbgDdQd7r5r4Pg/D2d9lfvcfU6elfbz7SjTq2G/r49wljC98bsu2tdF+Ljx9cOo3MT+kjB+k6/tqt9L/Cli49hy2Ey6lPrTlVOjexpH2eTKob46Jjxc0ESW3vijMeIZb4q6aDv6HLp82SIenGP32pSp6C154b7VKHKwONs9RY4iaTLnNOeaR15NUXBtvZAFsBnDI06VMBVZ40nyPS9EyfDrs9YXXtdH6B0P/q8iNfRAULz3HTLcERQSJG4UAmZ7JDHlrhCPqD1d4bKxxa+oeHOmd3UJOJ2WP1Ml/WW9c80l3jIve7Jay335oI8Tt0qWvfI7qwdvLTH3eSqDbMOc1hQh8c3qeO0x7fo4nTV6anMhofSMlvDAVzyW839Wrkq3HhwQ8qBAe+zNCg1wsYPuRCMYAHZkCL1ZjJWOBYiWGakjttOlpcxhOfOQk5q5UrhvJ3t9gN2Qn0dLkPZwH59yj57oKHyFH8ny2QBOvVWfszX4+WDK197aF+jfmc21jiwZNVTo0tvHNGzPVfDUIQIbPUgIiGttU4ajScid2W9mUaQ7buJ9vD21O8GhsYqzxgL+F74NGQdLNdPx9V+iOW3FYbLf6d6iAhrhitSJtl7g79Ua2Sg0bkVqiVqYTwvvFQBo0q6RC2GZWKxOJYFi4mioY47E6SWkdoueaWdzkELzqghi4UVJoy10QtHc1NqsYKaDYMVBsGMkzy86Cn8MgFgJPrnEBvnkOHVfDST9KeFX+NXNCasjQc7m3NJjf3/ACr3xlLXAyGI9rwy/GETWviogQzfpoSBPgEoL6ES9svTDIj2oufjIMxWWEiAG30eI0rPFdzHONtUSNgZYuuaOuxu2NJdc73fc054YIjGSVeqA4pGsMJc9S5LzU0thuPXjNUamIuVyneDlMCT56GSoeSuPAtX5Ky/gPP38jdkx4RNPK4hmMdNbFkzoxgO7tHWL4joUbv71+rjDXsh9lfXfUXY31zl2v3cG2mubgs+rg6phL1+NvlkbA50NWcvhadm41B6f/jU8qRDarWXnZZNFbjkjoauIDVAYRhohG7eUC4LPeqvGKfXYTDNAjy7/8tdfnOTXVj/NgVGU+uCTEmzkKBaAAfY/NRYU1imqXufkSokSo0WQuOv2dYskvA3AXHxejoqLtrQ/+2ioi5p/ActMcyxWLSxc/jKfupatxhd9d8Oj48td029WletcfAj6EzB09+c5XmRjG/j74Wq4K6t8880B2s3RmB64CSW1td2dlq7DY44Neyaz57LoYn2MCIT7GqcKNQ4YPOL/957fQ0tklatWoCE4l0UTY13T89j9ECMoZ2U2oceeiEuDZ8YErbvbrj7Th5zdEUILpLnPAdlBXhaCfiBA7RMpIQq71LlNqcE5sYd41KnUPA3ZUKiTLYUKYmTgvPe1FiE0jkroVk2XmbGa1HgZzCQDJMBZNB4z2zOGqC1zPlYbquow9lglVEgTq/84zU/Pxsw271STRsVkTatMlgrVNVNgKG3icMHj+O7IPOD691wI4xPCSjYf+nByN7haEM8m6z7LwWmyORRW207gCjav90eBv032SrTbmb/flp5PvQYm2rmrtXlhmptZ5WeAXm4t/s3XOTUsWnI51wNhQxtC1R5h/2UfIm+c5X3nYoIYrXeRqGqAWwSLywXRe1WInXcsyYamuBllUxGAjMx26BDIFZXE1UOkOM7SOclEzT4TirpFE+cJ+rrQk1q6ccZJpgJIdnIbWSeZ+aUTUbRnElYWtcdys7e8YDEC9BNlXg/23jma3jBKl9QS5rTWPDvjKf3FrjWbfsufEMj1pPIQ4tRc6r9/HIceeuQ1yoM9gSqsD/VYjcH2z6sr1C0K1QB8zzvLRro041JNtOHTKqTCmpxJtwLzYEJndm963gYN3+28fLnp+44p17x9OuWCj7Uwn9r3YBkLfNXeuglGZgCengUQoD4BU49UZjXNZsouc8+Bi1pzrFUSpYcWHHlDbmf7nwx6qL8OVBe49+M8D8cd8dmge8D3k4Tzrhb5ofWreDF7X87Fj643i2HwIu+q12eqSSzMSJKpKFpBsvN4YYNdUo26OvO6o7G5Y2yPxVxj5I6oHDw2ZH3DRbOiLxec1Z3pWRcpF2pEZS3MELe7wkDYUYP5LTfSE5rMp6Gzb1A37c6EZjJpirGvKLGx94ygIBGi4PXcYqgaictT7UK7SuN6YKpZJysRhqnlPBXbjXafGtgTu/ypCdGkvYTY+S3wyPeKrWt69st+ZRH1uZbr55fBwW/CYrrmuv7F7juMNl/PXkJWtNhmPaDiA8J7U0aQ1637Pip5nHeW3AtQy8uo2P4z09Dg+LuIBtyKVfU6Y5GCbzIgJvip6PNBHzAiiHVROWYs+mW3m4u2a9+dv8ntdVu7Iaf7VTn831rq51jwXLYHyVXGgzgC9fGQJsIXoiTUQWIz8IADqoAY9zXpLWN1PM/VE5Cp5mhNGTpCg2aLBwkS+GzmlfHaw5UZq19FEF4Hqk3bEkcF5Y1SOlhMNFGbQHNK1QSk3NixghOHckdDeEDeQs+OpG5tlqloCNNDYm4MuwrINoZLuL7xlNve4QX0+dyNaf4OFjwI5HZHwShu+NgnixpPs8kSa3rx9eC8s1rvmiBdywTCDOwsxkQODknxoLpDo5mpjTzZwBaglVS+khu0gUvsXrWk2NcZxylF3p6PbnpqLNCn/5KMaZjepxd7LyVpn20NR7dDE0NL1fXukcHfWykj+RJCQkdFFIu3ljALVlluHUZINA8wjpRMFYUN8TqvONKxFi0UaGl4NEkHECRZQ5zyGpfqknaKl+ykPh8kcVXBVEVIlopWRZUuBU1s5YzmFiCGwo3lZirpYbm5CSsSTpRRcnOYVnBUvJCUB6SpZxXAetKRUlN/zVL3hWtxVX89uKZjcf4EFsa/vUz68YGECphmQLqi5Y6s4ABQr7mxZQC8pUw/MAC12mvZ0kyhL68C18mc76rxDHjYFRfrXPIqTbsohXzlEQwlDRM/X9KxQYOxM96JsNoSPWJWpMGHPJsW7R1jxUfl0O06bTiHT0OXkLwvOXB1FLrcduh3K79zUTRuRQT6R7wxQBwZWghJTlPvoA2Ru+yMaEkKgKlplggh05Xh7/YCCUmrquxX8tjGOAwvNCfKJ+hIaGZM01au4m7b03e6ATvP6VcHFCpr0fCBxZ4WYudhpYbm+3m18tujE2GBvup5euQFXJtLOErPT18yto5t+PbJvo0uOYRP7/kyUaaU5PlHnWnRCHq/jNmBt0TYWo++BfCP2UZ0a4vqzPGLdNHPmY5vdddziSuuQa1U04XEvEUisqeGarksSVQD5DATYbyADJ0AeUDaazQKvihuB63NlhOLyze9nh+XvVAMf/FHjIQfm9TwYe/tQkUYxPJnnB9XN22ncTLHv4X17z2rb27wjUstkSuyP7HUXyiZZetOpYbOrBW5XBqVHhh5EMmd+NV1steakJ6BFJXaCDLY4jLIQFoql7bbupyWGtz1v777yHbZ/PX+pemXoyzfk/lg23614Xaxj3P/uWf/3vjcONT+pd//h+4vWdSHE83n8O3hmQrSBjLMfrsaFaMMwHybw21GHA8S0N9+kXgNLVRVeOYon7HyQdps6fBGldZO8O2pxak7YVC6mlQVZ+ldrucfrq5xXVP4q+YkfHXn5d2CSq8qlYCvEgglKcpb3vcRwCvaSrhbHLIdwDZx1e8ERPCW3ugIaKt5eAg9efXuzJumlevl+93rbQbY0XUNzhSZ5r94BFIbVThCVKDrFwkTIeI725b1fMaS7Rebk2HbMg7TlkSbTYNtvfBhIfloc+neff2zu+pDR+YHtj78dt30rep4q4WZ2VNFQaNyNJqFb0gG4jVwAJLjIxS5wyrIkcTOHUD9yJrGfiV7XK+6QvgnXdro5Ps8O2d+X8sYLW8p2VaPEAVY7eboVHo0zGuaA7j43aZvovOunedtyqQ8uctnmKh3jq9q/V4mo96ilI7H7cUIV1RBvJuP+s1T4Xo25CRNj9r2DgfBoOeuut82my/rEp+KGeNvqlpNOAydhEf6N6uzaHuzRmHmxtHdOAhvVP994lMImDmdAvDhik7qTdtGx/T7YE07UF8tHz73XaLXpnsI7VlK4bnYJMBzFw1PmQKK1GnUs1VrNJlJmSuwmZNPxUckLJX7bhPtzCNmlmMmm24b3KfX0rAbYV2I8/oLWX3A9QAht5fqseF8I89deal2NPwIHqvMxLmxRiG6RGi3rjxNK/+Be7kSwvqlbVuIfADK1/3OWhfv/L6DXV455HUwdlOfvaUjk+hv4f5gI2OuM3w02Ee08Q3xy5Y5c9pyDAfWheMJXnzFoxqTRLOm3gcgeZ66MMI+0Soj7awGZx/ebjJzWx0GzdVPAWJT2N4+s6/r0ue8Rql8JF7DrYoJfPOVSmdd5EZIK5wGuHJtORCseRFLFB+oTIXGE25Id+jUtnB8CoRatAaLpW0DsSUHH8WZDMJJUNwTNZQvJeZq8p1dImqnKxzlryY/393V7bbyo1Ef+Uiz0rAtUnmMcB8QZ4HAldbc2XJ0OKMAwwwPzI/N18yVUWyuyVb3uQAvgPkQc61m2yKtVedI51KDMI99F5xmEOXmFwepIQI0BsNawfPJOclDdFkq1iKRrmI6KeSS+nP5t07xxQc2GNDJs3TTO8MAfVHSoNckm4yFctTiqZKnoYmocpZD3OWW2KcrmQ/nyrp1+zivDeXlHhtizjrKByfv84IdFoxHtHJo1UQ77GX7JD6EAHv/Hq/rW4gUho2AqqeNFxtGkg/eJerP5ECJ1Z+jD3GcmNsmPJDXm/vcUdvGZKqb78iarnLRKI341teOxI1IP5UKMoXx0BiZGLRMG6t0pYLDQZWM8WLilw5y7J22oEVLXkQNuKQrn/OhLZC1ihJTVPTMRPMaf8qqYH3rRb06woRtg3VpN3phBL8d7H6/GFZecNiT7kOKcSiYfYDjRcFhIAi4sGHVWoD8L76jYuOmj9LtrQQASntj2h1OothTfERI8btFoziek2FanQ8MYNyIHu7hz/Gn/evwEtAiLjCpuDn5+DHJDuK6io3/sK61asBU7LEDvTiMgu+aB+U02pwWYdiitJJ24h8LzInHYwyEnnUrEzWJa2ZOJ+s7TXdDmt6IhMNeO3/wXQQll+LiTarfe0Ob47Rss5rfu7Nf+OCZ7f/bw1LDa4vhEGE9DD+dQXBAqWbKKFx0khOsGjxsCV0NwTbbpJwh7ntutqCGszhWd9a2WTRkomw5E3ujUfET91NDZx0hDNGTCv4U484RHDv18c0ZvBbKxMmWTbpDROEl5ovMJ1OwV7rwKeqWthv18cDmr/Nw2q77onOyuhO/uvscGC7cGKfBdpiBxkjQnEyrUDEwDOUxkgp4D31gMS8Mg46Dl4j1KHwkgXkV8pWqwjOH7XO2gBWKEUI5IL2BfxFBX6n47rIIpMbIOCLiI0I4Z3wISsbwjDkDAKsolf5vHV2fFEsdhFGQZfczgDfIr32Tb3ZUL0s0OCnr25WCGJS4c1WmJv7ioPzCDkMN3JF/wvpW+6WD/7P29Uvk0JDXpYHvJHLtO1DmySgxz2iEGcklqZfm5/1U42gnsc7fm7x88LblVt5u/O4yRjhteGrthZiMW4JvqLNs4DEYP7mfl/FDWzheluHGWmsl6DF9i1RMxO0ctyQkJK44rp1s3GaMH69EH0ZQWY6I9JIs3WxaWx8r8+NDAV1cyQrox70YEzKwhozMC9RRAN2f0DwaE3mYWBKZRu5jo4jAFMeBonSV4SVASnZCvMRi9tOmOST0iD1MgcdvQxOe801OKZWG++Kt4YQgT1EpRhccp0CH7JInBUl2FA4Z0ZLhGXNeTBcmTKgyc8yBhyFzkbG4mE1GaTWWb/g3J7co+kbO/d235we+uogMxe1QZMFvI7bsgSBQelbt6uJDVpzMJi/TBFcsYunLIz0pIbe2vI5NIN/R4zeZ4gaJ0zG90TGg7/d6hd1qRo51lplqqZ93zvHKu3NQ8vaxp0vpHz2x1DP5VBzwZN/jHiELX1b6j36IGfOdGan3TWk4WZaohxyreQj8OdnTdKIgC2aHEQRRNabNBhwuXXO0iUXWfLeSRtTToNUg3WKa6cgLFUgy1lnGmPz3ls7cBqnDn7IlkXQHVHkKDSTQiULqs2jPkEUAgQxiAEB30D5CPmkExOvTF5ORzKPX1/z4D/uDHxhue71j/zPDBfX7/Y93KxU4T0LPlV8P1Ga3732M0WYWgSZ++6dSLyxkx8pj4Ttk/vDH/Dp9nGO40YFzJZdRRrUgAni3oyGGBV9frXPHU/taGhWe+S82hC9aURmZNx0T0A38KkM3/hjrX3mDcU3VeTW4Ci8nC3aPhspIyTvXEGMB1gzxA2Mke76m/36UyKEV4qcittgnM1mSMxGl4QDeVYBnPmsmC6G2aBKjFmmaCwH5z5zXoLghQ8OjDv21PgM7js4A0L5ggE3opSKCAZbeWMH4yBOdyDJxoAuMDolKS18EjnAYklhmyiHjUaw4EMC8+9BpxBZMwT5EvyGgEllmeAhWFV1TvBB2yRdVC5nnUCj4FCEViZZD9qIM8ucUSEyYSGUkNj9KjBXEMGFUYNH5AbYk4eXMTropJGMwZ9RaE21MlQg9fLMFczZhX6rbvny2FsXlQsiSoPQ1GCecEDwterrL1HbtkY6bGeYCcYnq5krdvFC1bdTHe8pR/Xz+IhvSDHR+o3wWyVRrDXbuo9FA3YchXbRfrfujHC2KEZvOmRBMERj4qAh2bXePZxQahB3FIuMyi91RpcJou4k7P8gr3N7B9pxfQ3YWqJ6ML3j/OXHtV7RQRPhyis5bNAZnAshQHyFj5wni5MfxougjRMsOlkQpkhlHRJ8AP3EiobwQiZrEHNl8RPTQ8jBGMbhL8HdECVlw6JiA2gQ6ZlAUjDkB2PYjYHJcu485+C92Cx53eGMMi83CX/GqzhLhtdWwr+GoP1H1h3HzR3Kr18/rH5Bu+XnGe/xMi8JBoUEeHtEDdA7M5+qCf1ETcyWOG+l+sCCz2iE29XNLY59wL+gjI1PfRI43CGJ++6x5/6IdXbCsKQlOiM08nxhVWpKzRP6BDYugko5dNiYOzT4rXT5zrbEWbY91K6pS+9xbR8iz8ZGHJPPQeUitBaOG5asNEWWzAPOw8sUTIyp8GDRkwCznlwxILtWn3nw47YaUQQ1u4GfNOvX7bXcK/uhfiDR2UeqxYz+MzbozSG9KpBOz3BeKzfvXu1MaH4nXj08a2wv2m1akO3BYbxvotJJzxdUoMUS03Gfn6tV1QFkArJ47I58Z3Iem6bq9cdi8H51h644umZI/jxjBkLCP0Jof18qPtNOIdjYTy81k5zFzI9v0tY2SYiDre+xTb7MHjFu/dp+RKGyLIyHAk42i0iyLgbmmCOACoiVrWIyBgUBupcRLB+PyYNcWoitkd/2rPDbvnl0b2diODq47y57Xeo5/GLiRZOIk7VAPx9nP7Dfrva3j1/X1bL1vqXOi2Bz07Pzm+84STwxXqwO39DA3VUS2BYZN/ik8bG/zpoaJgGqJDB1+J5IMm622DRVQZrHhoouzNghAfKzXlMvw/4wYSfDYypj5gI7lSDWRtx0CJj6eGXvukmtoHVlr/14kP/9939QGPvMf9/xZKvrdnu2YDoCJMk53F7dwRgCxKesZBYTB8+TobcpQwL3NDrwUs1gIrigsXgFXmfyjoWC6SwG/+C9lJdNIKJjLP+x8RuUv+9NDkda9lfQA7/q5Mpc9vA4K48MfXpYpUffGgNxlzSj/3ni9+7VXogQT6kwybvazUQKFP5vO3+LkCwUuj2RIgqiqv8IQtpI2vLZTMqsEQPTSTdY5K7l5/sDlapXGyLdjLlXrbHpvZWgwHatsHOQXq0Zo9WOepRybeRP2zssTb0shr3x/1mmkDv/PY8gU3io3+hQK7DB9PNoKvtu4Hims8JcW+fAronyz6SHGqxR0hiRnNDKGMkZyGhASFurjFQKgdSkG5KOPPGkotJKWBtYHgI83IqnoDX14qB4nvx0j3A2JKkPOZHAjldpLqL5Hk40Y2b0kvP5Cn3f1w7r+gRJC7Impd/mirsALFEslp4ozT8/1vvoLs4E/rftDiwE3Mk7sLHbVFMfpxe3j7G1/makpz0esDUAjXBzVeeGCKT1BgRxQ/cbR9HyroWJ1OA/7fRkqGZO5vvaSBw25O0Pj+u8f5+zizFjf0Z/3ymGnL1hHUp9awD5WhWJM6u5AHsZguTS66y5lsr5YpMPTEFYiZ8xnhz8kLUZNEKGaFlEKBhMXraeU21h1vC7+OkPFIQdHkhL65+I52Wn9f1B5hevG83lOIJYJLibEwAhtTj1wK/6HGQrxwMaC5dXi++1i190lGvWFJ9OPO7zQlLt2MonczlPBtsWI0rV4swy9ynSmV3eZ/grP3MCXrSrTbL6q1OaxoMXfWhdXiDzHvuZPeqZj0IivoYIkrhzNsrMFecDTlQ7XjCRo4QR3IPnGsEgYmRZtJU6lpg5doQgqZZgwZ4x+PR3uRRAjo7rczWSLxdK/v1f/wNjmvUC"
PAYLOAD = json.loads(zlib.decompress(base64.b64decode(PAYLOAD_B64)).decode("utf-8"))

CURATED_UNITS: list[dict[str, Any]] = PAYLOAD["units"]
EXPECTED_PACKET_SHA256 = PAYLOAD["packet_sha"]
EXPECTED_ORDINALS = [int(x) for x in PAYLOAD["expected_ordinals"]]
EXPECTED_UNIT_COUNTS = {int(k): v for k, v in PAYLOAD["expected_unit_counts"].items()}
EXPECTED_UNIT_COUNT = 105
EXPECTED_PARAGRAPH_COUNT = 212
REPLACEMENT_DECODED_ORDINALS = {48,49,50,51,52,53,54,59,60,61,63,64,65}

MANAGED = [
    TEACHING_RECORDS,
    CURATION_INDEX,
    RESEARCH_MD,
    TEST,
    CATALOG,
    QUEUE,
    REPO_SCRIPT,
]


def die(message: str) -> None:
    raise SystemExit(f"ERROR: {message}")


def sh(cmd: list[str], *, capture: bool = False, check: bool = True):
    print("+", " ".join(cmd))
    return subprocess.run(
        cmd,
        cwd=ROOT,
        text=True,
        capture_output=capture,
        check=check,
    )


def now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def load_json(path: Path) -> Any:
    if not path.exists():
        die(f"Missing expected file: {path.relative_to(ROOT)}")
    return json.loads(path.read_text(encoding="utf-8"))


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        die(f"Missing expected file: {path.relative_to(ROOT)}")
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")


def ensure_repo_state() -> None:
    if not (ROOT / ".git").exists():
        die("Run this script from the pramana repo root.")

    branch = sh(["git", "branch", "--show-current"], capture=True).stdout.strip()
    if branch != EXPECTED_BRANCH:
        die(f"Expected branch {EXPECTED_BRANCH!r}; found {branch!r}")

    dirty = sh(["git", "status", "--porcelain"], capture=True).stdout.strip()
    if dirty:
        die("Working tree must be clean before curation.\n" + dirty)

    for path in (PRIVATE_PACKET, SCHEMA, CATALOG, QUEUE):
        if not path.exists():
            die(f"Missing required input: {path.relative_to(ROOT)}")

    if TEACHING_RECORDS.exists() or CURATION_INDEX.exists():
        die("Batch 046..065 artifacts already exist; refusing a second application.")


def validate_private_packet(packet: dict[str, Any]) -> dict[str, Any]:
    actual_sha = hashlib.sha256(PRIVATE_PACKET.read_bytes()).hexdigest()
    if actual_sha != EXPECTED_PACKET_SHA256:
        die(
            "Private packet SHA drifted.\n"
            f"expected {EXPECTED_PACKET_SHA256}\n"
            f"actual   {actual_sha}"
        )

    if packet.get("packet_version") != "1.0":
        die(f"Expected packet version 1.0; found {packet.get('packet_version')!r}")

    selection = packet.get("selection", {})
    if (
        selection.get("selected_count") != 20
        or selection.get("start_ordinal") != 46
        or selection.get("end_ordinal") != 65
    ):
        die(f"Unexpected batch selection metadata: {selection}")

    if packet.get("rights", {}).get("public_export_allowed") is not False:
        die("Private packet rights gate is not fail-closed.")

    if packet.get("chapter_count") != 20:
        die("Expected chapter_count=20.")
    if packet.get("paragraph_count") != EXPECTED_PARAGRAPH_COUNT:
        die(
            f"Expected {EXPECTED_PARAGRAPH_COUNT} source paragraphs; "
            f"found {packet.get('paragraph_count')}"
        )

    by_ordinal = {c["ordinal"]: c for c in packet["chapters"]}
    if sorted(by_ordinal) != EXPECTED_ORDINALS:
        die(
            "Unexpected batch ordinals.\n"
            f"expected={EXPECTED_ORDINALS}\n"
            f"actual={sorted(by_ordinal)}"
        )

    actual_replacement = {
        ordinal
        for ordinal, chapter in by_ordinal.items()
        if chapter["decoded_as"] == "utf-8-replacement"
    }
    if actual_replacement != REPLACEMENT_DECODED_ORDINALS:
        die(
            "Replacement-decoded source set drifted.\n"
            f"expected={sorted(REPLACEMENT_DECODED_ORDINALS)}\n"
            f"actual={sorted(actual_replacement)}"
        )

    if len(CURATED_UNITS) != EXPECTED_UNIT_COUNT:
        die(f"Expected {EXPECTED_UNIT_COUNT} curated units; found {len(CURATED_UNITS)}")
    if len({u["id"] for u in CURATED_UNITS}) != EXPECTED_UNIT_COUNT:
        die("Curated teaching-unit IDs are not unique.")

    used: dict[int, list[str]] = defaultdict(list)

    for unit in CURATED_UNITS:
        if unit["proposed_authority"] != "dk_attested":
            die(f"Unexpected authority promotion: {unit['id']}")
        if unit.get("historical_witness") is not None:
            die(f"Unexpected historical witness: {unit['id']}")

        chapter = by_ordinal.get(unit["chapter_ordinal"])
        if not chapter:
            die(f"Missing source chapter for {unit['id']}")

        para_by_id = {p["id"]: p for p in chapter["paragraphs"]}
        if len(unit["source_paragraph_ids"]) != len(unit["source_paragraph_hashes"]):
            die(f"Paragraph id/hash count mismatch in {unit['id']}")

        for pid, expected_hash in zip(
            unit["source_paragraph_ids"],
            unit["source_paragraph_hashes"],
        ):
            para = para_by_id.get(pid)
            if not para:
                die(f"Missing paragraph {unit['chapter_ordinal']}:{pid}")
            if para["sha256"] != expected_hash:
                die(
                    f"Paragraph hash drift for {unit['id']} {pid}:\n"
                    f"expected {expected_hash}\n"
                    f"actual   {para['sha256']}"
                )
            used[unit["chapter_ordinal"]].append(pid)

        has_decode_flag = "source_decode_replacement" in unit.get("flags", [])
        if unit["chapter_ordinal"] in REPLACEMENT_DECODED_ORDINALS and not has_decode_flag:
            die(f"Replacement-decoded source unit lacks flag: {unit['id']}")
        if unit["chapter_ordinal"] not in REPLACEMENT_DECODED_ORDINALS and has_decode_flag:
            die(f"Clean UTF-8 source unit has replacement flag: {unit['id']}")

    total_used = 0
    for ordinal, chapter in by_ordinal.items():
        all_ids = [p["id"] for p in chapter["paragraphs"]]
        covered = used[ordinal]
        total_used += len(covered)
        if Counter(covered) != Counter(all_ids):
            missing = sorted(set(all_ids) - set(covered))
            duplicate = sorted(pid for pid, n in Counter(covered).items() if n > 1)
            extra = sorted(set(covered) - set(all_ids))
            die(
                f"Source coverage mismatch for ordinal {ordinal}: "
                f"missing={missing} duplicate={duplicate} extra={extra}"
            )

    if total_used != EXPECTED_PARAGRAPH_COUNT:
        die(
            f"Expected exactly {EXPECTED_PARAGRAPH_COUNT} covered source paragraphs; "
            f"found {total_used}"
        )

    return {
        "packet_sha256": actual_sha,
        "generated_at": packet.get("generated_at"),
        "chapter_count": packet["chapter_count"],
        "paragraph_count": packet["paragraph_count"],
        "by_ordinal": by_ordinal,
    }


def make_teaching_records(packet_meta: dict[str, Any], catalog: dict[str, Any]) -> list[dict[str, Any]]:
    catalog_by_url = {c["url"]: c for c in catalog["chapters"]}
    records: list[dict[str, Any]] = []

    for unit in CURATED_UNITS:
        chapter = packet_meta["by_ordinal"][unit["chapter_ordinal"]]
        if chapter["url"] not in catalog_by_url:
            die(f"Catalog row missing for {unit['id']}")

        pids = ",".join(unit["source_paragraph_ids"])
        phashes = ",".join(unit["source_paragraph_hashes"])

        records.append({
            "id": unit["id"],
            "corpus": "mahaperiyava_teachings",
            "work": "deivathin_kural",
            "teacher": "chandrasekharendra_saraswati",
            "compiler": "ra_ganapathi",
            "language": "tamil",
            "source_locus": {
                "volume": 1,
                "section_title_ta": None,
                "chapter_title_ta": chapter["title_ta"],
                "chapter_ordinal": chapter["ordinal"],
                "print_edition": None,
                "print_page_start": None,
                "print_page_end": None,
                "digital_url": chapter["url"],
                "digital_anchor": None,
            },
            "claim_summary": unit["claim_summary"],
            "topics": unit["topics"],
            "attribution": {
                "dk_attestation": "located",
                "wording_status": "dk_wording_only",
                "compiler_intervention_status": "unknown",
                "note": (
                    "Curator-authored summary, not a quotation. Official Kanchi "
                    "digital Deivathin Kural attests this teaching. Exact primary "
                    "wording is not established. Historical-witness comparison "
                    "has not yet been performed for this batch."
                ),
            },
            "evidence_status": {
                "digital_attestation": "confirmed",
                "print_check": "not_checked",
                "primary_source_status": "unknown",
                "authority": "dk_attested",
            },
            "provenance": [{
                "source_key": chapter["source_key"],
                "witness_role": "official_digital",
                "url": chapter["url"],
                "locus": f"private batch review packet paragraph(s) {pids}",
                "snapshot_sha256": chapter["snapshot_sha256"],
                "lineage_note": (
                    "Official Kanchi digital Deivathin Kural is a descendant "
                    "of the Ra. Ganapathi compilation and is not treated as "
                    "an independent primary witness."
                ),
                "rights_status": "restricted_private_research",
            }],
            "rights": {
                "source_text_tier": "restricted",
                "public_export": "metadata_only",
                "terms_url": None,
                "note": (
                    "Exact source wording remains only in private/gitignored "
                    "snapshots and review packets."
                ),
            },
            "flags": list(unit.get("flags", [])),
            "curator_notes": (
                f"Private batch packet refs={pids}; "
                f"paragraph_sha256={phashes}; "
                f"source_packet_sha256={packet_meta['packet_sha256']}. "
                "Summary is metadata, not a quotation."
            ),
        })

    return records


def schema_shape_validate(records: list[dict[str, Any]]) -> None:
    schema = load_json(SCHEMA)
    top_allowed = set(schema["properties"])
    top_required = set(schema["required"])
    id_re = re.compile(schema["properties"]["id"]["pattern"])

    for record in records:
        missing = top_required - set(record)
        extra = set(record) - top_allowed
        if missing:
            die(f"Schema required fields missing in {record['id']}: {sorted(missing)}")
        if extra:
            die(f"Schema extra fields in {record['id']}: {sorted(extra)}")
        if not id_re.match(record["id"]):
            die(f"Teaching-record ID fails schema pattern: {record['id']}")

        for field in ("source_locus", "attribution", "evidence_status", "rights"):
            spec = schema["properties"][field]
            obj = record[field]
            required = set(spec.get("required", []))
            allowed = set(spec.get("properties", {}))
            if required - set(obj):
                die(f"{record['id']}.{field} missing {sorted(required-set(obj))}")
            if spec.get("additionalProperties") is False and set(obj) - allowed:
                die(f"{record['id']}.{field} extra {sorted(set(obj)-allowed)}")

        if record["evidence_status"]["authority"] != "dk_attested":
            die(f"Unexpected authority promotion: {record['id']}")
        if record["evidence_status"]["print_check"] != "not_checked":
            die(f"Unexpected print-check promotion: {record['id']}")
        if record["evidence_status"]["primary_source_status"] != "unknown":
            die(f"Unexpected primary-source promotion: {record['id']}")
        if record["attribution"]["wording_status"] != "dk_wording_only":
            die(f"Unexpected wording status: {record['id']}")
        if (
            record["rights"]["source_text_tier"] == "restricted"
            and record["rights"]["public_export"] not in {"metadata_only", "none"}
        ):
            die(f"Restricted-rights gate violated: {record['id']}")


def make_curation_index(packet_meta: dict[str, Any], records: list[dict[str, Any]]) -> dict[str, Any]:
    unit_counts = Counter(u["chapter_ordinal"] for u in CURATED_UNITS)
    flag_counts = Counter(
        flag for unit in CURATED_UNITS for flag in unit.get("flags", [])
    )

    return {
        "version": "0.1",
        "corpus": "mahaperiyava_teachings",
        "work": "deivathin_kural",
        "volume": 1,
        "phase": "batch_046_065_teaching_units_curated",
        "status": "CURATED_REVIEW_DATA_NOT_PUBLICATION_APPROVED",
        "generated_at": now_iso(),
        "source_packet": {
            "packet_version": "1.0",
            "private_path": "data/private/mahaperiyava_dk_v1_batch_046_065_review_packet.json",
            "sha256": packet_meta["packet_sha256"],
            "generated_at": packet_meta["generated_at"],
            "chapter_count": packet_meta["chapter_count"],
            "paragraph_count": packet_meta["paragraph_count"],
            "contains_restricted_source_text": True,
            "tracked": False,
        },
        "policy": {
            "no_exact_source_text_in_tracked_artifacts": True,
            "claim_summaries_are_not_quotes": True,
            "all_batch_authority_is_dk_attested": True,
            "historical_witness_comparison_deferred": True,
            "no_print_check_claimed": True,
            "no_primary_source_verified_claimed": True,
            "every_source_paragraph_mapped_exactly_once": True,
            "replacement_decoded_source_units_are_flagged": True,
            "source_title_anomalies_preserved_pending_qc": True,
            "sensitive_external_fact_claims_are_flagged": True,
            "social_and_religious_generalizations_are_attributed_only": True,
            "caste_varna_material_requires_contextual_answering": True,
            "political_material_requires_source_attribution": True,
            "violence_punishment_and_sacrifice_material_requires_context": True,
            "human_publication_review_still_required": True,
        },
        "source_anomalies": [{
            "chapter_ordinal": 61,
            "field": "title_ta",
            "observed": packet_meta["by_ordinal"][61]["title_ta"],
            "action": "preserved_pending_source_qc",
        }],
        "unit_count": len(records),
        "authority_counts": {"dk_attested": len(records)},
        "chapter_unit_counts": {
            str(o): unit_counts[o] for o in sorted(unit_counts)
        },
        "flag_counts": dict(sorted(flag_counts.items())),
        "source_coverage": {
            "paragraph_count": packet_meta["paragraph_count"],
            "covered_paragraph_count": packet_meta["paragraph_count"],
            "coverage_mode": "exactly_once",
            "excluded_source_blocks": 0,
        },
        "units": [{
            "id": u["id"],
            "chapter_ordinal": u["chapter_ordinal"],
            "chapter_slug": u["chapter_slug"],
            "unit_slug": u["unit_slug"],
            "claim_summary": u["claim_summary"],
            "question_intents": u["question_intents"],
            "source_paragraph_ids": u["source_paragraph_ids"],
            "source_paragraph_hashes": u["source_paragraph_hashes"],
            "topics": u["topics"],
            "flags": u["flags"],
            "authority": "dk_attested",
            "historical_witness": None,
        } for u in CURATED_UNITS],
    }


def update_queue_and_catalog(catalog: dict[str, Any]) -> None:
    counts = Counter(u["chapter_ordinal"] for u in CURATED_UNITS)
    selected = set(EXPECTED_ORDINALS)

    queue = load_jsonl(QUEUE)
    seen = set()

    for row in queue:
        if row["ordinal"] not in selected:
            continue
        if row["pilot"]:
            die(f"Unexpected pilot ordinal in this batch: {row['ordinal']}")
        if row["stage"] != "needs_teaching_unit_review":
            die(f"Ordinal {row['ordinal']} already has stage={row['stage']}")
        if row["teaching_units_created"] != 0:
            die(f"Ordinal {row['ordinal']} already has teaching units.")

        row["stage"] = "batch_teaching_units_curated"
        row["teaching_units_created"] = counts[row["ordinal"]]
        row["review_notes"] = (
            "Curated metadata-only teaching units from private hashed review "
            "packet. Authority remains dk_attested; historical-witness "
            "comparison, print check, and primary-source verification remain pending."
        )
        seen.add(row["ordinal"])

    if seen != selected:
        die(f"Queue selection mismatch: missing={sorted(selected-seen)}")
    write_jsonl(QUEUE, queue)

    seen_catalog = set()
    for chapter in catalog["chapters"]:
        if chapter["ordinal"] in selected:
            chapter["review_status"] = "batch_teaching_units_curated"
            chapter["teaching_unit_count"] = counts[chapter["ordinal"]]
            seen_catalog.add(chapter["ordinal"])

    if seen_catalog != selected:
        die(f"Catalog selection mismatch: missing={sorted(selected-seen_catalog)}")
    write_json(CATALOG, catalog)


def write_tests() -> None:
    TEST.parent.mkdir(parents=True, exist_ok=True)
    TEST.write_text(
        r'''from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
RECORDS = ROOT / "data/review/mahaperiyava_dk_v1_batch_046_065_teaching_records.jsonl"
INDEX = ROOT / "data/review/mahaperiyava_dk_v1_batch_046_065_curation_index.json"
QUEUE = ROOT / "data/review/mahaperiyava_deivathin_kural_v1_extraction_queue.jsonl"
SCHEMA = ROOT / "schema/teaching_record.schema.json"

EXPECTED = set(range(46, 66))
REPLACEMENT_DECODED = {48,49,50,51,52,53,54,59,60,61,63,64,65}


def _json(path):
    return json.loads(path.read_text(encoding="utf-8"))


def _jsonl(path):
    return [
        json.loads(x)
        for x in path.read_text(encoding="utf-8").splitlines()
        if x.strip()
    ]


def test_batch_shape_and_authority():
    rows = _jsonl(RECORDS)
    index = _json(INDEX)

    assert len(rows) == 105
    assert index["unit_count"] == 105
    assert len({r["id"] for r in rows}) == 105
    assert {r["source_locus"]["chapter_ordinal"] for r in rows} == EXPECTED
    assert Counter(r["evidence_status"]["authority"] for r in rows) == {
        "dk_attested": 105
    }
    assert all(r["evidence_status"]["print_check"] == "not_checked" for r in rows)
    assert all(r["evidence_status"]["primary_source_status"] == "unknown" for r in rows)
    assert all(r["attribution"]["wording_status"] == "dk_wording_only" for r in rows)


def test_schema_shape_and_rights():
    schema = _json(SCHEMA)
    rows = _jsonl(RECORDS)
    top_allowed = set(schema["properties"])
    top_required = set(schema["required"])
    id_re = re.compile(schema["properties"]["id"]["pattern"])

    for row in rows:
        assert not (top_required - set(row))
        assert not (set(row) - top_allowed)
        assert id_re.match(row["id"])
        assert "text" not in row
        assert "exact_text_restricted" not in row
        assert row["rights"]["source_text_tier"] == "restricted"
        assert row["rights"]["public_export"] == "metadata_only"


def test_all_212_source_paragraphs_are_mapped_once():
    index = _json(INDEX)
    coverage = index["source_coverage"]

    assert coverage == {
        "paragraph_count": 212,
        "covered_paragraph_count": 212,
        "coverage_mode": "exactly_once",
        "excluded_source_blocks": 0,
    }

    seen = []
    for unit in index["units"]:
        assert unit["question_intents"]
        assert len(unit["source_paragraph_ids"]) == len(unit["source_paragraph_hashes"])
        assert all(re.fullmatch(r"[0-9a-f]{64}", h) for h in unit["source_paragraph_hashes"])
        seen.extend(
            (unit["chapter_ordinal"], pid)
            for pid in unit["source_paragraph_ids"]
        )

    assert len(seen) == 212
    assert len(set(seen)) == 212


def test_replacement_decoded_units_are_flagged():
    rows = _jsonl(RECORDS)
    for row in rows:
        ordinal = row["source_locus"]["chapter_ordinal"]
        flagged = "source_decode_replacement" in row.get("flags", [])
        assert flagged is (ordinal in REPLACEMENT_DECODED)


def test_chapter_61_title_anomaly_is_preserved():
    rows = _jsonl(RECORDS)
    index = _json(INDEX)

    ch61 = [r for r in rows if r["source_locus"]["chapter_ordinal"] == 61]
    assert ch61
    assert all(r["source_locus"]["chapter_title_ta"] == "அன்பu" for r in ch61)

    anomaly = index["source_anomalies"][0]
    assert anomaly["chapter_ordinal"] == 61
    assert anomaly["observed"] == "அன்பu"
    assert anomaly["action"] == "preserved_pending_source_qc"


def test_context_sensitive_material_stays_at_dk_attested():
    rows = _jsonl(RECORDS)
    sensitive = {
        "caste_varna_normative_claim",
        "historical_claim_requires_external_verification",
        "political_historical_claim",
        "political_normative_claim",
        "religious_comparison_attributed_only",
        "scientific_claim_requires_external_verification",
        "medical_or_effect_claim_attributed_only",
        "health_claim_attributed_only",
        "hagiographic_tradition",
        "social_generalization",
        "cultural_generalization",
    }

    flagged = [r for r in rows if sensitive.intersection(r.get("flags", []))]
    assert flagged
    assert all(r["evidence_status"]["authority"] == "dk_attested" for r in flagged)


def test_ahimsa_force_and_sacrifice_claim_is_contextualized():
    rows = _jsonl(RECORDS)
    target = next(
        r for r in rows
        if r["id"].endswith(".contextual_exceptions_to_absolute_ahimsa")
    )
    assert target["evidence_status"]["authority"] == "dk_attested"
    assert "traditional_normative_claim" in target["flags"]
    assert "religious_comparison_attributed_only" in target["flags"]


def test_political_chapters_remain_attributed():
    rows = _jsonl(RECORDS)
    selected = [
        r for r in rows
        if r["source_locus"]["chapter_ordinal"] in {62,63,64}
    ]
    assert selected
    assert all(r["evidence_status"]["authority"] == "dk_attested" for r in selected)
    assert any("political_normative_claim" in r.get("flags", []) for r in selected)


def test_queue_counts_match_index():
    queue = _jsonl(QUEUE)
    index = _json(INDEX)
    counts = {int(k): v for k, v in index["chapter_unit_counts"].items()}
    selected = [q for q in queue if q["ordinal"] in EXPECTED]

    assert len(selected) == 20
    assert all(q["stage"] == "batch_teaching_units_curated" for q in selected)
    assert all(q["teaching_units_created"] == counts[q["ordinal"]] for q in selected)


def test_policy_fail_closed():
    policy = _json(INDEX)["policy"]
    assert policy["historical_witness_comparison_deferred"] is True
    assert policy["every_source_paragraph_mapped_exactly_once"] is True
    assert policy["sensitive_external_fact_claims_are_flagged"] is True
    assert policy["caste_varna_material_requires_contextual_answering"] is True
    assert policy["political_material_requires_source_attribution"] is True
    assert policy["violence_punishment_and_sacrifice_material_requires_context"] is True
''',
        encoding="utf-8",
    )


def write_research_md(packet_meta: dict[str, Any]) -> None:
    counts = Counter(u["chapter_ordinal"] for u in CURATED_UNITS)
    flag_counts = Counter(
        flag for unit in CURATED_UNITS for flag in unit.get("flags", [])
    )

    lines = [
        "# Mahaperiyava — Deivathin Kural Volume 1 Batch 046–065",
        "",
        "## Result",
        "",
        "- New chapters curated: **20**",
        "- New teaching units: **105**",
        "- `dk_attested`: **105**",
        "- `earlier_witness_supported`: **0 new promotions**",
        "- `dk_print_checked`: **0**",
        "- `primary_source_verified`: **0**",
        "- Private review-packet paragraphs: **212**",
        "- Source paragraph coverage: **212/212 exactly once**",
        "- Explicitly excluded source blocks: **0**",
        "",
        "Exact Deivathin Kural wording remains private. Curator summaries are "
        "metadata, not quotations.",
        "",
        "## Evidence discipline",
        "",
        "- Official Kanchi DK establishes DK attestation only.",
        "- Historical-witness comparison is deferred.",
        "- No print check or primary-source verification is claimed.",
        "- Replacement-decoded chapters are explicitly flagged.",
        "- Chapter 61's mixed-script source title is preserved pending source QC.",
        "- Context-sensitive claims remain attributed rather than exported as "
        "neutral external fact.",
        "",
        "## High-context material",
        "",
        "- dharma-shastra authority versus individual conscience;",
        "- varna/caste and claims about earlier social organization;",
        "- contextual exceptions to ahimsa: war, punishment and sacrifice;",
        "- Hindu/Buddhist/Jain comparative claims;",
        "- ancestor rites and unseen ritual transmission;",
        "- hagiographic claims about perfected truthfulness;",
        "- dietary and plant-sentience claims using scientific language;",
        "- colonial-era cultural and political claims about swarajya;",
        "- claims that temples, moral exemplars, education, or service causally "
        "change society or spiritual states.",
        "",
        "## Units per chapter",
        "",
    ]

    for ordinal in sorted(counts):
        title = packet_meta["by_ordinal"][ordinal]["title_ta"]
        lines.append(f"- {ordinal:03d} `{title}`: **{counts[ordinal]}**")

    lines += ["", "## Flag highlights", ""]
    for flag, count in sorted(flag_counts.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"- `{flag}`: **{count}**")

    lines += [
        "",
        "## Next gate",
        "",
        "Run a targeted 1957–58 historical-witness pass only on high-yield "
        "claims with plausible earlier parallels: common dharma disciplines, "
        "ahimsa/satya, puja/bhakti, service, desire/anger, and selected "
        "dharma-shastra formulations. Do not promote caste/varna, political, "
        "historical, or comparative-religion claims merely because a related "
        "theme appears in an earlier collection.",
        "",
    ]

    RESEARCH_MD.parent.mkdir(parents=True, exist_ok=True)
    RESEARCH_MD.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def install_repo_script() -> None:
    REPO_SCRIPT.parent.mkdir(parents=True, exist_ok=True)
    src = Path(__file__).resolve()
    if src != REPO_SCRIPT.resolve():
        shutil.copyfile(src, REPO_SCRIPT)
        REPO_SCRIPT.chmod(0o755)


def snapshot_managed():
    return {p: (p.read_bytes() if p.exists() else None) for p in MANAGED}


def restore_managed(snapshot) -> None:
    print("\n=== Validation failed: restoring managed files ===")
    sh(["git", "reset"], check=False)
    for path, old in snapshot.items():
        if old is None:
            if path.exists():
                path.unlink()
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(old)
    sh(["git", "status", "--short"], check=False)


def validate_after(records, index) -> None:
    if len(records) != EXPECTED_UNIT_COUNT:
        die(f"Expected 105 records; found {len(records)}")

    if Counter(r["evidence_status"]["authority"] for r in records) != Counter({"dk_attested": 105}):
        die("Authority distribution drifted.")

    actual_counts = Counter(r["source_locus"]["chapter_ordinal"] for r in records)
    if actual_counts != Counter(EXPECTED_UNIT_COUNTS):
        die(
            "Chapter unit-count drift.\n"
            f"expected={EXPECTED_UNIT_COUNTS}\nactual={dict(actual_counts)}"
        )

    if index["source_coverage"]["covered_paragraph_count"] != EXPECTED_PARAGRAPH_COUNT:
        die("Source paragraph coverage drifted.")


def run_checks() -> None:
    print("\n=== Repo checks ===")
    sh(["git", "diff", "--check"])
    sh([sys.executable, "-m", "pytest", "-q"])
    sh([sys.executable, "scripts/audit_snapshots.py"])
    sh(["git", "diff", "--stat"])
    sh(["git", "status", "--short"])


def commit_changes() -> None:
    paths = [str(p.relative_to(ROOT)) for p in MANAGED if p.exists()]
    sh(["git", "add", "--", *paths])

    unstaged = sh(["git", "diff", "--name-only"], capture=True).stdout.strip()
    if unstaged:
        die("Unexpected unstaged changes remain; refusing to commit.\n" + unstaged)

    staged = sh(["git", "diff", "--cached", "--name-only"], capture=True).stdout.strip()
    if not staged:
        die("Nothing staged to commit.")

    print("\nStaged files:")
    print(staged)
    sh(["git", "commit", "-m", "Curate Mahaperiyava DK V1 batch 046-065"])


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--commit", action="store_true")
    parser.add_argument("--push", action="store_true")
    args = parser.parse_args()

    if args.push and not args.commit:
        die("--push requires --commit")

    ensure_repo_state()
    before = snapshot_managed()

    try:
        packet = load_json(PRIVATE_PACKET)
        packet_meta = validate_private_packet(packet)
        catalog = load_json(CATALOG)

        records = make_teaching_records(packet_meta, catalog)
        schema_shape_validate(records)
        index = make_curation_index(packet_meta, records)

        write_jsonl(TEACHING_RECORDS, records)
        write_json(CURATION_INDEX, index)
        update_queue_and_catalog(catalog)
        write_tests()
        write_research_md(packet_meta)
        install_repo_script()
        validate_after(records, index)

        print("\n=== Batch 046..065 curation summary ===")
        print("Chapters curated:              20")
        print("Teaching units:               105")
        print("Source paragraphs:            212")
        print("Paragraph coverage:       212/212")
        print("dk_attested:                  105")
        print("earlier witness promotions:     0")
        print("print checked:                  0")
        print("primary verified:               0")
        print("source exclusions:              0")
        print("Tracked exact DK source text: NONE")

        run_checks()

    except Exception:
        restore_managed(before)
        raise

    if args.commit:
        commit_changes()
    else:
        print("\nChanges validated but not committed.")

    if args.push:
        sh(["git", "push", "origin", EXPECTED_BRANCH])

    print("\n=== Final ===")
    sh(["git", "status", "--short"])
    sh(["git", "log", "-5", "--oneline"])


if __name__ == "__main__":
    main()
