(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const views={home:$("#homeView"),ask:$("#askView"),explore:$("#exploreView"),saved:$("#savedView")};
const askForm=$("#askForm"),questionInput=$("#questionInput"),answerRegion=$("#answerRegion"),micButton=$("#micButton"),voiceStatus=$("#voiceStatus"),speechLanguage=$("#speechLanguage"),savedList=$("#savedList"),promptGrid=$("#promptGrid"),clearSaved=$("#clearSaved"),evidenceTemplate=$("#evidenceTemplate");
const prompts=["What does Mahaperiyava say about Advaita and nonduality?","Does Mahaperiyava teach the essential unity of Shiva and Vishnu?","What does Mahaperiyava say about Kamakshi and compassion?","Why invoke Ganesha before beginning an undertaking?","What does the discourse say about uncertain traditions of Pallava origins?","சிவனும் விஷ்ணுவும் ஒன்றா?"];
function navigate(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle("active",k===name));$$('.nav').forEach(b=>b.classList.toggle("active",b.dataset.nav===name));if(name==="saved")renderSaved();window.scrollTo({top:0,behavior:"smooth"});}
$$('[data-nav]').forEach(b=>b.addEventListener("click",()=>navigate(b.dataset.nav)));
function node(tag,value,cls){const n=document.createElement(tag);if(cls)n.className=cls;n.textContent=value;return n;}
function evidenceFragment(hit,i){const f=evidenceTemplate.content.cloneNode(true),source=hit.source||{},status=hit.evidence_status||{};f.querySelector('.evidence-title').textContent=`Evidence ${i+1} · V${source.volume}, chapter ${source.chapter_ordinal}`;f.querySelector('.authority').textContent=status.authority||'attested';f.querySelector('.evidence-summary').textContent=hit.claim_summary||'';f.querySelector('.evidence-meta').textContent=`${hit.support_id} · ${source.chapter_title_ta||'chapter title unavailable'}`;f.querySelector('.context-note').hidden=!hit.context_required;return f;}
function renderPacket(packet){answerRegion.replaceChildren();const card=document.createElement('section');card.className='card answer-card';if(!packet.answerable){card.classList.add('status-card');card.append(node('h3','Insufficient evidence'),node('p',packet.message||'No sufficiently strong corpus match was found.','muted'));answerRegion.append(card);return;}card.append(node('h3','Grounded answer'),node('p',packet.answer.display_text,'answer-lead'));const save=node('button','Save answer','secondary');save.type='button';save.addEventListener('click',()=>savePacket(packet));card.append(save,node('h4','Evidence','evidence-heading'));packet.evidence.forEach((hit,i)=>card.append(evidenceFragment(hit,i)));card.append(node('p','Curator summaries are not verbatim quotations. Open evidence to inspect source locus and authority.','muted small'));answerRegion.append(card);}
async function ask(question){const q=question.trim();if(!q)return;answerRegion.replaceChildren(node('div','Retrieving attested evidence…','card muted'));document.body.classList.add('loading');try{const response=await fetch('/v1/mahaperiyava/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,top_k:8})});const packet=await response.json();if(!response.ok)throw new Error(packet.error||'Request failed');renderPacket(packet);}catch(err){answerRegion.replaceChildren();const card=document.createElement('div');card.className='card status-card';card.append(node('h3','Could not reach the local Pramāṇa service'),node('p',String(err.message||err),'muted'));answerRegion.append(card);}finally{document.body.classList.remove('loading');}}
askForm.addEventListener('submit',event=>{event.preventDefault();ask(questionInput.value);});
function storageGet(){try{return JSON.parse(localStorage.getItem('pramana.mahaperiyava.saved')||'[]');}catch{return[];}}
function storageSet(items){localStorage.setItem('pramana.mahaperiyava.saved',JSON.stringify(items.slice(0,50)));}
function savePacket(packet){const saved=storageGet();saved.unshift({savedAt:new Date().toISOString(),query:packet.query,displayText:packet.answer.display_text,supportIds:packet.claims.flatMap(c=>c.support_ids)});storageSet(saved);}
function renderSaved(){savedList.replaceChildren();const saved=storageGet();if(!saved.length){savedList.append(node('p','No saved answers yet.','muted'));return;}saved.forEach(item=>{const w=document.createElement('article');w.className='saved-item';w.append(node('div',item.query,'saved-question'),node('div',item.displayText,'saved-answer'),node('div',`${item.supportIds.length} evidence link(s)`,'muted small'));savedList.append(w);});}
clearSaved.addEventListener('click',()=>{storageSet([]);renderSaved();});
prompts.forEach(prompt=>{const b=node('button',prompt,'prompt');b.type='button';b.addEventListener('click',()=>{questionInput.value=prompt;navigate('ask');questionInput.focus();});promptGrid.append(b);});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,listening=false;if(SpeechRecognition){recognition=new SpeechRecognition();recognition.continuous=false;recognition.interimResults=true;recognition.onstart=()=>{listening=true;micButton.setAttribute('aria-pressed','true');micButton.textContent='■ Stop';voiceStatus.textContent='Listening… transcript stays editable.';};recognition.onresult=event=>{let transcript='';for(let i=event.resultIndex;i<event.results.length;i+=1)transcript+=event.results[i][0].transcript;if(transcript){const prefix=questionInput.value.trim();questionInput.value=`${prefix}${prefix?' ':''}${transcript}`.trim();}// Voice input only edits the transcript; it never submits the form.
};recognition.onerror=event=>{voiceStatus.textContent=`Dictation unavailable: ${event.error}. You can continue typing.`;};recognition.onend=()=>{listening=false;micButton.setAttribute('aria-pressed','false');micButton.textContent='🎙 Dictate';voiceStatus.textContent='Review or edit the transcript, then submit when ready.';};micButton.addEventListener('click',()=>{if(listening){recognition.stop();return;}recognition.lang=speechLanguage.value;recognition.start();});}else{micButton.disabled=true;voiceStatus.textContent='Browser dictation is unavailable here. Type your question instead.';}
renderSaved();})();
